/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.aidil.view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import org.aidil.controller.WisatawanCotroller;

/**
 *
 * @author Aidil
 */
public class DialogWisatawan extends javax.swing.JDialog {

    /**
     * Creates new form DialogWisatawan
     */
    WisatawanCotroller wisatawanCotroller;
    FormPemesanan formPemesanan;
    public DialogWisatawan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        formPemesanan = (FormPemesanan)parent;
        wisatawanCotroller = new WisatawanCotroller(this);
        wisatawanCotroller.viewDataDialog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtfwn = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdwn = new javax.swing.JTable();
        btnfwn = new javax.swing.JButton();
        btnpwn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Kode/Nama Wisatawan");

        tbdwn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Wisatawan", "Nama Wisatawan", "Telepon"
            }
        ));
        jScrollPane1.setViewportView(tbdwn);

        btnfwn.setText("FILTER");
        btnfwn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfwnActionPerformed(evt);
            }
        });

        btnpwn.setText("PILIH");
        btnpwn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpwnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtfwn)
                        .addGap(18, 18, 18)
                        .addComponent(btnfwn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnpwn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtfwn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfwn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnpwn)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnfwnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfwnActionPerformed
        // TODO add your handling code here:
        wisatawanCotroller.viewDataDialog();
    }//GEN-LAST:event_btnfwnActionPerformed

    private void btnpwnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpwnActionPerformed
        // TODO add your handling code here:
        formPemesanan.getTxtidwn().setText(tbdwn.getValueAt(tbdwn.getSelectedRow(),0).toString());
        formPemesanan.getTxtnw().setText(tbdwn.getValueAt(tbdwn.getSelectedRow(),1).toString());
        dispose();
    }//GEN-LAST:event_btnpwnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogWisatawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogWisatawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogWisatawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogWisatawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogWisatawan dialog = new DialogWisatawan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public WisatawanCotroller getWisatawanCotroller() {
        return wisatawanCotroller;
    }

    public void setWisatawanCotroller(WisatawanCotroller wisatawanCotroller) {
        this.wisatawanCotroller = wisatawanCotroller;
    }
     

    public JButton getBtnfwn() {
        return btnfwn;
    }

    public void setBtnfwn(JButton btnfwn) {
        this.btnfwn = btnfwn;
    }

    public JButton getBtnpwn() {
        return btnpwn;
    }

    public void setBtnpwn(JButton btnpwn) {
        this.btnpwn = btnpwn;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTable getTbdwn() {
        return tbdwn;
    }

    public void setTbdwn(JTable tbdwn) {
        this.tbdwn = tbdwn;
    }

    public JTextField getTxtfwn() {
        return txtfwn;
    }

    public void setTxtfwn(JTextField txtfwn) {
        this.txtfwn = txtfwn;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnfwn;
    private javax.swing.JButton btnpwn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbdwn;
    private javax.swing.JTextField txtfwn;
    // End of variables declaration//GEN-END:variables
}
