/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.aidil.view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import org.aidil.controller.PaketTravelController;

/**
 *
 * @author Aidil
 */
public class DialogPaketTravel extends javax.swing.JDialog {

    /**
     * Creates new form DialogPaketTravel
     */
    PaketTravelController paketTravelController;
    FormPemesanan formPemesanan;
    public DialogPaketTravel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        formPemesanan = (FormPemesanan)parent;
        paketTravelController = new PaketTravelController(this);
        paketTravelController.viewDataDialog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtfdpt = new javax.swing.JTextField();
        btnfdpt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdpt = new javax.swing.JTable();
        btnpdpt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Kode Paket wisata");

        txtfdpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfdptActionPerformed(evt);
            }
        });

        btnfdpt.setText("FILTER");
        btnfdpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfdptActionPerformed(evt);
            }
        });

        tbdpt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Paket Travel", "ID Wisata", "Nama Wisata", "Tarif Wisata", "ID Transportas", "Nama Kendaraan", "Tarif Transportasi", "ID Penginapan", "Nama Penginapan", "Tarif Penginapan", "Lama Wisata", "Jumlah Rombongan"
            }
        ));
        jScrollPane1.setViewportView(tbdpt);

        btnpdpt.setText("PILIH");
        btnpdpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpdptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnpdpt)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtfdpt, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnfdpt))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtfdpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfdpt))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnpdpt)
                .addContainerGap(303, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfdptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfdptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfdptActionPerformed

    private void btnfdptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfdptActionPerformed
        // TODO add your handling code here:
        paketTravelController.viewDataDialog();
    }//GEN-LAST:event_btnfdptActionPerformed

    private void btnpdptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpdptActionPerformed
        // TODO add your handling code here:
        formPemesanan.getTxtidpk().setText(tbdpt.getValueAt(tbdpt.getSelectedRow(),0).toString());
        formPemesanan.getTxtidw().setText(tbdpt.getValueAt(tbdpt.getSelectedRow(),1).toString());
        formPemesanan.getTxtnwpt().setText(tbdpt.getValueAt(tbdpt.getSelectedRow(),2).toString());
        formPemesanan.getTvTarifWisata().setText(tbdpt.getValueAt(tbdpt.getSelectedRow(),3).toString());
        formPemesanan.getTxtidt().setText(tbdpt.getValueAt(tbdpt.getSelectedRow(),4).toString());
        formPemesanan.getTxtnkps().setText(tbdpt.getValueAt(tbdpt.getSelectedRow(),5).toString());
        formPemesanan.getTvTarifTransportasi().setText(tbdpt.getValueAt(tbdpt.getSelectedRow(),6).toString());
        formPemesanan.getTxtidpp().setText(tbdpt.getValueAt(tbdpt.getSelectedRow(),7).toString());
        formPemesanan.getTxtnpps().setText(tbdpt.getValueAt(tbdpt.getSelectedRow(),8).toString());
        formPemesanan.getTvTarifPenginapan().setText(tbdpt.getValueAt(tbdpt.getSelectedRow(),9).toString());
        formPemesanan.getTxtlw().setText(tbdpt.getValueAt(tbdpt.getSelectedRow(),10).toString());
        formPemesanan.getTxtjr().setText(tbdpt.getValueAt(tbdpt.getSelectedRow(),11).toString());
        dispose();
    }//GEN-LAST:event_btnpdptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogPaketTravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogPaketTravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogPaketTravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogPaketTravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogPaketTravel dialog = new DialogPaketTravel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public JButton getBtnfdpt() {
        return btnfdpt;
    }

    public void setBtnfdpt(JButton btnfdpt) {
        this.btnfdpt = btnfdpt;
    }

    public JButton getBtnpdpt() {
        return btnpdpt;
    }

    public void setBtnpdpt(JButton btnpdpt) {
        this.btnpdpt = btnpdpt;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTable getTbdpt() {
        return tbdpt;
    }

    public void setTbdpt(JTable tbdpt) {
        this.tbdpt = tbdpt;
    }

    public JTextField getTxtfdpt() {
        return txtfdpt;
    }

    public void setTxtfdpt(JTextField txtfdpt) {
        this.txtfdpt = txtfdpt;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnfdpt;
    private javax.swing.JButton btnpdpt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbdpt;
    private javax.swing.JTextField txtfdpt;
    // End of variables declaration//GEN-END:variables
}
