/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.aidil.view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import org.aidil.controller.WisataController;

/**
 *
 * @author Aidil
 */
public class DialogWisataPaketTravel extends javax.swing.JDialog {

    /**
     * Creates new form DialogWisataPaketTravel
     */
    WisataController wisataController;
    FormPaketTravel formPaketTravel;
    public DialogWisataPaketTravel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        formPaketTravel = (FormPaketTravel)parent;
        wisataController = new WisataController(this);
        wisataController.viewDataDialog1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtknmdwpt = new javax.swing.JTextField();
        btnfdwpt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdwpt = new javax.swing.JTable();
        btnpdwpt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Kode / Nama Wisata");

        btnfdwpt.setText("FILTER");
        btnfdwpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfdwptActionPerformed(evt);
            }
        });

        tbdwpt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Wisata", "Nama Wisata", "Tarif Wisata"
            }
        ));
        jScrollPane1.setViewportView(tbdwpt);

        btnpdwpt.setText("PILIH");
        btnpdwpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpdwptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtknmdwpt, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnfdwpt)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnpdwpt)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtknmdwpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfdwpt))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnpdwpt)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpdwptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpdwptActionPerformed
        // TODO add your handling code here:
        formPaketTravel.getTxtidwpt().setText(tbdwpt.getValueAt(tbdwpt.getSelectedRow(),0).toString());
        formPaketTravel.getTxtnmpt().setText(tbdwpt.getValueAt(tbdwpt.getSelectedRow(),1).toString());
        formPaketTravel.getTxttarifwisPatra().setText(tbdwpt.getValueAt(tbdwpt.getSelectedRow(),2).toString());
        dispose();
    }//GEN-LAST:event_btnpdwptActionPerformed

    private void btnfdwptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfdwptActionPerformed
        // TODO add your handling code here:
        wisataController.viewDataDialog1();
    }//GEN-LAST:event_btnfdwptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogWisataPaketTravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogWisataPaketTravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogWisataPaketTravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogWisataPaketTravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogWisataPaketTravel dialog = new DialogWisataPaketTravel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public JButton getBtnfdwpt() {
        return btnfdwpt;
    }

    public void setBtnfdwpt(JButton btnfdwpt) {
        this.btnfdwpt = btnfdwpt;
    }

    public JButton getBtnpdwpt() {
        return btnpdwpt;
    }

    public void setBtnpdwpt(JButton btnpdwpt) {
        this.btnpdwpt = btnpdwpt;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTable getTbdwpt() {
        return tbdwpt;
    }

    public void setTbdwpt(JTable tbdwpt) {
        this.tbdwpt = tbdwpt;
    }

    public JTextField getTxtknmdwpt() {
        return txtknmdwpt;
    }

    public void setTxtknmdwpt(JTextField txtknmdwpt) {
        this.txtknmdwpt = txtknmdwpt;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnfdwpt;
    private javax.swing.JButton btnpdwpt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbdwpt;
    private javax.swing.JTextField txtknmdwpt;
    // End of variables declaration//GEN-END:variables
}
