/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.aidil.view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import org.aidil.controller.PenginapanController;

/**
 *
 * @author Aidil
 */
public class DialogPenginapanPaketTravel extends javax.swing.JDialog {

    /**
     * Creates new form DialogPenginapanPaketTravel
     */
    PenginapanController penginapanController;
    FormPaketTravel formPaketTravel;
    public DialogPenginapanPaketTravel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        formPaketTravel = (FormPaketTravel)parent;
        penginapanController = new PenginapanController(this);
        penginapanController.viewDataDialog1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtfdppt = new javax.swing.JTextField();
        btnfdppt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdppt = new javax.swing.JTable();
        btnpdppt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("jLabel1");

        btnfdppt.setText("FILTER");
        btnfdppt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfdpptActionPerformed(evt);
            }
        });

        tbdppt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Penginapan", "Nama Penginapan", "Tarif Penginapan"
            }
        ));
        jScrollPane1.setViewportView(tbdppt);
        if (tbdppt.getColumnModel().getColumnCount() > 0) {
            tbdppt.getColumnModel().getColumn(2).setResizable(false);
        }

        btnpdppt.setText("PILIH");
        btnpdppt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpdpptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtfdppt, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnfdppt)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnpdppt)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtfdppt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfdppt))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnpdppt)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnfdpptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfdpptActionPerformed
        // TODO add your handling code here:
        penginapanController.viewDataDialog1();
    }//GEN-LAST:event_btnfdpptActionPerformed

    private void btnpdpptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpdpptActionPerformed
        // TODO add your handling code here:
        formPaketTravel.getTxtidpppt().setText(tbdppt.getValueAt(tbdppt.getSelectedRow(),0).toString());
        formPaketTravel.getTxtnpppt().setText(tbdppt.getValueAt(tbdppt.getSelectedRow(),1).toString());
        formPaketTravel.getTxttppt().setText(tbdppt.getValueAt(tbdppt.getSelectedRow(),2).toString());
        dispose();
    }//GEN-LAST:event_btnpdpptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogPenginapanPaketTravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogPenginapanPaketTravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogPenginapanPaketTravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogPenginapanPaketTravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogPenginapanPaketTravel dialog = new DialogPenginapanPaketTravel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public JButton getBtnfdppt() {
        return btnfdppt;
    }

    public void setBtnfdppt(JButton btnfdppt) {
        this.btnfdppt = btnfdppt;
    }

    public JButton getBtnpdppt() {
        return btnpdppt;
    }

    public void setBtnpdppt(JButton btnpdppt) {
        this.btnpdppt = btnpdppt;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTable getTbdppt() {
        return tbdppt;
    }

    public void setTbdppt(JTable tbdppt) {
        this.tbdppt = tbdppt;
    }

    public JTextField getTxtfdppt() {
        return txtfdppt;
    }

    public void setTxtfdppt(JTextField txtfdppt) {
        this.txtfdppt = txtfdppt;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnfdppt;
    private javax.swing.JButton btnpdppt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbdppt;
    private javax.swing.JTextField txtfdppt;
    // End of variables declaration//GEN-END:variables
}
