/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.aidil.view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import org.aidil.controller.GuideController;

/**
 *
 * @author Aidil
 */
public class FormGuide extends javax.swing.JFrame {

    /**
     * Creates new form FormGuide
     */
    GuideController guideController;
    public FormGuide() {
        initComponents();
        guideController = new GuideController(this);
        guideController.bersihForm();
        guideController.tampilTable();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txttpg = new javax.swing.JTextField();
        txtag = new javax.swing.JTextField();
        txtidg = new javax.swing.JTextField();
        txtng = new javax.swing.JTextField();
        txttfg = new javax.swing.JTextField();
        btncg = new javax.swing.JButton();
        btnig = new javax.swing.JButton();
        btnug = new javax.swing.JButton();
        btndg = new javax.swing.JButton();
        btnccg = new javax.swing.JButton();
        btnexg = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbg = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Guide");

        jLabel2.setText("Nama Guide");

        jLabel3.setText("Telepon");

        jLabel4.setText("Alamat");

        jLabel5.setText("Tarif Guide");

        txttpg.setText("jTextField1");
        txttpg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttpgActionPerformed(evt);
            }
        });

        txtag.setText("jTextField1");

        txtidg.setText("jTextField1");

        txtng.setText("jTextField1");

        txttfg.setText("jTextField1");

        btncg.setText("CARI");
        btncg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncgActionPerformed(evt);
            }
        });

        btnig.setText("INSERT");
        btnig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnigActionPerformed(evt);
            }
        });

        btnug.setText("UPDATE");
        btnug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnugActionPerformed(evt);
            }
        });

        btndg.setText("DELETE");
        btndg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndgActionPerformed(evt);
            }
        });

        btnccg.setText("CANCEL");
        btnccg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnccgActionPerformed(evt);
            }
        });

        btnexg.setText("EXIT");
        btnexg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexgActionPerformed(evt);
            }
        });

        tbg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Guide", "Nama Guide", "Alamat", "Telepon", "Tarif Guide"
            }
        ));
        tbg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbgMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbg);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel2))
                                    .addGap(51, 51, 51)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txttpg, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtag, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtng, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtidg)
                                        .addComponent(txttfg))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btncg))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btnig)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnug)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btndg)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnccg)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnexg))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtidg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncg))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txttpg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txttfg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnig)
                    .addComponent(btnug)
                    .addComponent(btndg)
                    .addComponent(btnccg)
                    .addComponent(btnexg))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(341, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncgActionPerformed
        // TODO add your handling code here:
        guideController.cariData();
    }//GEN-LAST:event_btncgActionPerformed

    private void txttpgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttpgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttpgActionPerformed

    private void btnigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnigActionPerformed
        // TODO add your handling code here:
        guideController.insert();
        guideController.bersihForm();
        guideController.tampilTable();
    }//GEN-LAST:event_btnigActionPerformed

    private void btnugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnugActionPerformed
        // TODO add your handling code here:
        guideController.update();
        guideController.bersihForm();
        guideController.tampilTable();
    }//GEN-LAST:event_btnugActionPerformed

    private void btndgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndgActionPerformed
        // TODO add your handling code here:
        guideController.delete();
        guideController.bersihForm();
        guideController.tampilTable();
    }//GEN-LAST:event_btndgActionPerformed

    private void btnccgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnccgActionPerformed
        // TODO add your handling code here:
        guideController.bersihForm();
    }//GEN-LAST:event_btnccgActionPerformed

    private void btnexgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexgActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnexgActionPerformed

    private void tbgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbgMouseClicked
        // TODO add your handling code here:
        guideController.pilihTabel();
    }//GEN-LAST:event_tbgMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormGuide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormGuide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormGuide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormGuide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormGuide().setVisible(true);
            }
        });
    }

    public JButton getjButton1() {
        return btncg;
    }

    public void setjButton1(JButton jButton1) {
        this.btncg = jButton1;
    }

    public JButton getjButton2() {
        return btnig;
    }

    public void setjButton2(JButton jButton2) {
        this.btnig = jButton2;
    }

    public JButton getjButton3() {
        return btnug;
    }

    public void setjButton3(JButton jButton3) {
        this.btnug = jButton3;
    }

    public JButton getjButton4() {
        return btndg;
    }

    public void setjButton4(JButton jButton4) {
        this.btndg = jButton4;
    }

    public JButton getjButton5() {
        return btnccg;
    }

    public void setjButton5(JButton jButton5) {
        this.btnccg = jButton5;
    }

    public JButton getjButton6() {
        return btnexg;
    }

    public void setjButton6(JButton jButton6) {
        this.btnexg = jButton6;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JTextField getTxtag() {
        return txtag;
    }

    public void setTxtag(JTextField txtag) {
        this.txtag = txtag;
    }

    public JTextField getTxtidg() {
        return txtidg;
    }

    public void setTxtidg(JTextField txtidg) {
        this.txtidg = txtidg;
    }

    public JTextField getTxtng() {
        return txtng;
    }

    public void setTxtng(JTextField txtng) {
        this.txtng = txtng;
    }

    public JTextField getTxttfg() {
        return txttfg;
    }

    public void setTxttfg(JTextField txttfg) {
        this.txttfg = txttfg;
    }

    public JTextField getTxttpg() {
        return txttpg;
    }

    public void setTxttpg(JTextField txttpg) {
        this.txttpg = txttpg;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTable getTbg() {
        return tbg;
    }

    public void setTbg(JTable tbg) {
        this.tbg = tbg;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnccg;
    private javax.swing.JButton btncg;
    private javax.swing.JButton btndg;
    private javax.swing.JButton btnexg;
    private javax.swing.JButton btnig;
    private javax.swing.JButton btnug;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbg;
    private javax.swing.JTextField txtag;
    private javax.swing.JTextField txtidg;
    private javax.swing.JTextField txtng;
    private javax.swing.JTextField txttfg;
    private javax.swing.JTextField txttpg;
    // End of variables declaration//GEN-END:variables
}
