/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.aidil.view;

import datechooser.beans.DateChooserCombo;
import java.awt.Dimension;
import java.text.SimpleDateFormat;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import org.aidil.controller.PaketTravelController;

/**
 *
 * @author Aidil
 */

public class FormPaketTravel extends javax.swing.JFrame {

    /**
     * Creates new form FormPaketTravel
     */
    PaketTravelController paketTravelController;
    public FormPaketTravel() {
        initComponents();
        paketTravelController = new PaketTravelController(this);
        paketTravelController.bersihForm();
        paketTravelController.tampilTable();
       // paketTravelController.isiWisata();
        //paketTravelController.isiTransportasi();
       // paketTravelController.isiPenginapan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtidpt = new javax.swing.JTextField();
        btncpt = new javax.swing.JButton();
        btnipt = new javax.swing.JButton();
        btnept = new javax.swing.JButton();
        btndpt = new javax.swing.JButton();
        btnccpt = new javax.swing.JButton();
        btnexpt = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbpt = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtlwpt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtidwpt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtnmpt = new javax.swing.JTextField();
        txtidtpt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtnnkpt = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        txtidpppt = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtnpppt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtjrpt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txttarifwisPatra = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtttpt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txttppt = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Paket Travel");

        jLabel3.setText("ID Wisata");

        jLabel4.setText("ID Transportasi");

        jLabel6.setText("ID Penginapan");

        txtidpt.setText("jTextField1");

        btncpt.setText("CARI");
        btncpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncptActionPerformed(evt);
            }
        });

        btnipt.setText("INSERT");
        btnipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btniptActionPerformed(evt);
            }
        });

        btnept.setText("EDIT");
        btnept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneptActionPerformed(evt);
            }
        });

        btndpt.setText("DELETE");
        btndpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndptActionPerformed(evt);
            }
        });

        btnccpt.setText("CANCEL");
        btnccpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnccptActionPerformed(evt);
            }
        });

        btnexpt.setText("EXIT");
        btnexpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexptActionPerformed(evt);
            }
        });

        tbpt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Paket Travel", "ID Wisata", "Nama Wisata", "Tarif Wisata", "ID Transportasi", "Nama Transportasi", "Tarif Wisata", "ID Penginapan", "Nama Penginapan", "Tarif Penginapan", "Lama Wisata (Hari)", "Jumlah Rombongan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbpt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbptMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbpt);

        jLabel8.setText("Lama Wisata");

        jLabel9.setText("Hari");

        jButton1.setText(".....");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama Wisata");

        jLabel5.setText("Nama Kendaraan");

        jButton2.setText(".....");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText(".....");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setText("Nama Penginapan");

        jLabel10.setText("Jumlah Rombongan");

        txtjrpt.setText("jTextField1");
        txtjrpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjrptActionPerformed(evt);
            }
        });

        jLabel11.setText("Tarif Wisata");

        jLabel12.setText("Tarif transportasi");

        jLabel13.setText("Tarif Penginapan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtidwpt, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton1))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txttarifwisPatra, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtidtpt, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtnmpt, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton2))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtidpt, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btncpt))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtidpppt, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton3))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txtttpt, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtnnkpt, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtnpppt, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txttppt, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(txtlwpt)
                                                    .addComponent(txtjrpt, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel9))))))
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel11)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnipt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnept)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btndpt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnccpt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnexpt))
                            .addComponent(jLabel12)
                            .addComponent(jLabel7)
                            .addComponent(jLabel13)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10))
                        .addContainerGap(1065, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtidpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncpt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidwpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel3))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnmpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txttarifwisPatra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtidtpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtnnkpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtttpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtidpppt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtnpppt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txttppt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtlwpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtjrpt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnipt)
                    .addComponent(btnept)
                    .addComponent(btndpt)
                    .addComponent(btnccpt)
                    .addComponent(btnexpt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncptActionPerformed
        // TODO add your handling code here:
        paketTravelController.cariData();
    }//GEN-LAST:event_btncptActionPerformed

    private void btniptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btniptActionPerformed
        // TODO add your handling code here:
        paketTravelController.insert();
        paketTravelController.bersihForm();
        paketTravelController.tampilTable();
    }//GEN-LAST:event_btniptActionPerformed

    private void btneptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneptActionPerformed
        // TODO add your handling code here:
        paketTravelController.update();
        paketTravelController.bersihForm();
        paketTravelController.tampilTable();
    }//GEN-LAST:event_btneptActionPerformed

    private void btndptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndptActionPerformed
        // TODO add your handling code here:
        paketTravelController.delete();
        paketTravelController.bersihForm();
        paketTravelController.tampilTable();
    }//GEN-LAST:event_btndptActionPerformed

    private void btnccptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnccptActionPerformed
        // TODO add your handling code here:
        paketTravelController.bersihForm();
    }//GEN-LAST:event_btnccptActionPerformed

    private void btnexptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexptActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnexptActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DialogWisataPaketTravel dialogWisataPaketTravel = new DialogWisataPaketTravel(this, true);
        dialogWisataPaketTravel.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DialogTransportasiPaketTravel dialogTransportasiPaketTravel = new DialogTransportasiPaketTravel(this,true);
        dialogTransportasiPaketTravel.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DialogPenginapanPaketTravel dialogPenginapanPaketTravel = new DialogPenginapanPaketTravel(this, true);
        dialogPenginapanPaketTravel.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tbptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbptMouseClicked
        // TODO add your handling code here:
        paketTravelController.pilihTabel();
        
    }//GEN-LAST:event_tbptMouseClicked

    private void txtjrptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjrptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjrptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPaketTravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPaketTravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPaketTravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPaketTravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPaketTravel().setVisible(true);
            }
        });
    }

    public JButton getBtnccpt() {
        return btnccpt;
    }

    public void setBtnccpt(JButton btnccpt) {
        this.btnccpt = btnccpt;
    }

    public JButton getBtncpt() {
        return btncpt;
    }

    public void setBtncpt(JButton btncpt) {
        this.btncpt = btncpt;
    }

    public JButton getBtndpt() {
        return btndpt;
    }

    public void setBtndpt(JButton btndpt) {
        this.btndpt = btndpt;
    }

    public JButton getBtnept() {
        return btnept;
    }

    public void setBtnept(JButton btnept) {
        this.btnept = btnept;
    }

    public JButton getBtnexpt() {
        return btnexpt;
    }

    public void setBtnexpt(JButton btnexpt) {
        this.btnexpt = btnexpt;
    }

    public JButton getBtnipt() {
        return btnipt;
    }

    public void setBtnipt(JButton btnipt) {
        this.btnipt = btnipt;
    }

  /** public JComboBox<String> getCbidp() {
        return cbidp;
    }

    public void setCbidp(JComboBox<String> cbidp) {
        this.cbidp = cbidp;
    }*/
    
    

   /** public JComboBox<String> getCbidt() {
        return cbidt;
    }

    public void setCbidt(JComboBox<String> cbidt) {
        this.cbidt = cbidt;
    } */

   /** public JComboBox<String> getCbidwa() {
        return cbidwa;
    }

    public void setCbidwa(JComboBox<String> cbidwa) {
        this.cbidwa = cbidwa;
    }*/

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JTextField getTxtlwpt() {
        return txtlwpt;
    }

    public void setTxtlwpt(JTextField txtlwpt) {
        this.txtlwpt = txtlwpt;
    }

    

    public PaketTravelController getPaketTravelController() {
        return paketTravelController;
    }

    public void setPaketTravelController(PaketTravelController paketTravelController) {
        this.paketTravelController = paketTravelController;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JScrollPane getjScrollPane3() {
        return jScrollPane3;
    }

    public void setjScrollPane3(JScrollPane jScrollPane3) {
        this.jScrollPane3 = jScrollPane3;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public JTable getjTable2() {
        return jTable2;
    }

    public void setjTable2(JTable jTable2) {
        this.jTable2 = jTable2;
    }

    public JTable getTbpt() {
        return tbpt;
    }

    public void setTbpt(JTable tbpt) {
        this.tbpt = tbpt;
    }

    public JTextField getTxtidpt() {
        return txtidpt;
    }

    public void setTxtidpt(JTextField txtidpt) {
        this.txtidpt = txtidpt;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JTextField getTxtidwpt() {
        return txtidwpt;
    }

    public void setTxtidwpt(JTextField txtidwpt) {
        this.txtidwpt = txtidwpt;
    }

    public JTextField getTxtnmpt() {
        return txtnmpt;
    }

    public void setTxtnmpt(JTextField txtnmpt) {
        this.txtnmpt = txtnmpt;
    }

    public JButton getjButton2() {
        return jButton2;
    }

    public void setjButton2(JButton jButton2) {
        this.jButton2 = jButton2;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JTextField getTxtidtpt() {
        return txtidtpt;
    }

    public void setTxtidtpt(JTextField txtidtpt) {
        this.txtidtpt = txtidtpt;
    }

    public JTextField getTxtnnkpt() {
        return txtnnkpt;
    }

    public void setTxtnnkpt(JTextField txtnnkpt) {
        this.txtnnkpt = txtnnkpt;
    }

    public JButton getjButton3() {
        return jButton3;
    }

    public void setjButton3(JButton jButton3) {
        this.jButton3 = jButton3;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JTextField getTxtidpppt() {
        return txtidpppt;
    }

    public void setTxtidpppt(JTextField txtidpppt) {
        this.txtidpppt = txtidpppt;
    }

    public JTextField getTxtnpppt() {
        return txtnpppt;
    }

    public void setTxtnpppt(JTextField txtnpppt) {
        this.txtnpppt = txtnpppt;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JTextField getTxtjrpt() {
        return txtjrpt;
    }

    public void setTxtjrpt(JTextField txtjrpt) {
        this.txtjrpt = txtjrpt;
    }

    public JTextField getTxttarifwisPatra() {
        return txttarifwisPatra;
    }

    public void setTxttarifwisPatra(JTextField txttarifwisPatra) {
        this.txttarifwisPatra = txttarifwisPatra;
    }

    public JTextField getTxttppt() {
        return txttppt;
    }

    public void setTxttppt(JTextField txttppt) {
        this.txttppt = txttppt;
    }

    public JTextField getTxtttpt() {
        return txtttpt;
    }

    public void setTxtttpt(JTextField txtttpt) {
        this.txtttpt = txtttpt;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnccpt;
    private javax.swing.JButton btncpt;
    private javax.swing.JButton btndpt;
    private javax.swing.JButton btnept;
    private javax.swing.JButton btnexpt;
    private javax.swing.JButton btnipt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tbpt;
    private javax.swing.JTextField txtidpppt;
    private javax.swing.JTextField txtidpt;
    private javax.swing.JTextField txtidtpt;
    private javax.swing.JTextField txtidwpt;
    private javax.swing.JTextField txtjrpt;
    private javax.swing.JTextField txtlwpt;
    private javax.swing.JTextField txtnmpt;
    private javax.swing.JTextField txtnnkpt;
    private javax.swing.JTextField txtnpppt;
    private javax.swing.JTextField txttarifwisPatra;
    private javax.swing.JTextField txttppt;
    private javax.swing.JTextField txtttpt;
    // End of variables declaration//GEN-END:variables
}
