/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.aidil.view;

import java.text.Normalizer;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JTextField;
import org.aidil.controller.MenuController;
import org.aidil.model.JenisWisata;

/**
 *
 * @author Aidil
 */
public class FormMenu extends javax.swing.JFrame {
    MenuController menuController;

    /**
     * Creates new form NewJFrame
     */
    public FormMenu() {
        initComponents();
        menuController = new MenuController(this);
        menuController.nonAktif();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuGuide = new javax.swing.JMenuItem();
        menuJenisPenginapan = new javax.swing.JMenuItem();
        menuJenisTransportasi = new javax.swing.JMenuItem();
        menuJenisWisata = new javax.swing.JMenuItem();
        menuPaketTravel = new javax.swing.JMenuItem();
        menuPenginapan = new javax.swing.JMenuItem();
        menuTransportasi = new javax.swing.JMenuItem();
        menuUser = new javax.swing.JMenuItem();
        menuWisata = new javax.swing.JMenuItem();
        menuWisatawan = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuPemesanan = new javax.swing.JMenuItem();
        menuPembayaran = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuLaporanPembayaran = new javax.swing.JMenuItem();
        menuLaporanPemesanan = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("jMenu3");

        jMenuItem2.setText("jMenuItem2");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("LOGIN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnLogin)
                                .addGap(36, 36, 36)
                                .addComponent(btnCancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addComponent(btnLogout))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(33, 33, 33))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(35, 35, 35)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUsername)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnCancel)
                    .addComponent(btnLogout))
                .addContainerGap())
        );

        jMenu1.setText("Master");

        menuGuide.setText("Guide");
        menuGuide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGuideActionPerformed(evt);
            }
        });
        jMenu1.add(menuGuide);

        menuJenisPenginapan.setText("Jenis Penginapan");
        menuJenisPenginapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuJenisPenginapanActionPerformed(evt);
            }
        });
        jMenu1.add(menuJenisPenginapan);

        menuJenisTransportasi.setText("Jenis Transportasi");
        menuJenisTransportasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuJenisTransportasiActionPerformed(evt);
            }
        });
        jMenu1.add(menuJenisTransportasi);

        menuJenisWisata.setText("Jenis Wisata");
        menuJenisWisata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuJenisWisataActionPerformed(evt);
            }
        });
        jMenu1.add(menuJenisWisata);

        menuPaketTravel.setText("Paket Travel");
        menuPaketTravel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPaketTravelActionPerformed(evt);
            }
        });
        jMenu1.add(menuPaketTravel);

        menuPenginapan.setText("Penginapan");
        menuPenginapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPenginapanActionPerformed(evt);
            }
        });
        jMenu1.add(menuPenginapan);

        menuTransportasi.setText("Transportasi");
        menuTransportasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTransportasiActionPerformed(evt);
            }
        });
        jMenu1.add(menuTransportasi);

        menuUser.setText("User");
        menuUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUserActionPerformed(evt);
            }
        });
        jMenu1.add(menuUser);

        menuWisata.setText("Wisata");
        menuWisata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuWisataActionPerformed(evt);
            }
        });
        jMenu1.add(menuWisata);

        menuWisatawan.setText("Wisatawan");
        menuWisatawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuWisatawanActionPerformed(evt);
            }
        });
        jMenu1.add(menuWisatawan);

        jMenuBar1.add(jMenu1);

        jMenu6.setText("Transaksi");

        menuPemesanan.setText("Pemesanan");
        menuPemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPemesananActionPerformed(evt);
            }
        });
        jMenu6.add(menuPemesanan);

        menuPembayaran.setText("Pembayaran");
        menuPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPembayaranActionPerformed(evt);
            }
        });
        jMenu6.add(menuPembayaran);

        jMenuBar1.add(jMenu6);

        jMenu2.setText("Laporan");

        MenuLaporanPembayaran.setText("Laporan Pembayaran");
        MenuLaporanPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLaporanPembayaranActionPerformed(evt);
            }
        });
        jMenu2.add(MenuLaporanPembayaran);

        menuLaporanPemesanan.setText("Laporan Pemesanan");
        menuLaporanPemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLaporanPemesananActionPerformed(evt);
            }
        });
        jMenu2.add(menuLaporanPemesanan);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuGuideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGuideActionPerformed
        // TODO add your handling code here:
        FormGuide guide = new FormGuide();
        guide.setVisible(true);
    }//GEN-LAST:event_menuGuideActionPerformed

    private void menuWisatawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuWisatawanActionPerformed
        // TODO add your handling code here:
        FormWisatawan wisatawan = new FormWisatawan();
        wisatawan.setVisible(true);
    }//GEN-LAST:event_menuWisatawanActionPerformed

    private void menuJenisTransportasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuJenisTransportasiActionPerformed
        // TODO add your handling code here:
        FormJenisTransportasi jenisTransportasi = new FormJenisTransportasi();
        jenisTransportasi.setVisible(true);
    }//GEN-LAST:event_menuJenisTransportasiActionPerformed

    private void menuPemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPemesananActionPerformed
        // TODO add your handling code here:
        FormPemesanan pemesanan = new FormPemesanan();
        pemesanan.setVisible(true);
    }//GEN-LAST:event_menuPemesananActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        menuController.cekLogin();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void menuJenisPenginapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuJenisPenginapanActionPerformed
        // TODO add your handling code here:
        FormJenisPenginapan jenisPenginapan = new FormJenisPenginapan();
        jenisPenginapan.setVisible(true);
    }//GEN-LAST:event_menuJenisPenginapanActionPerformed

    private void menuJenisWisataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuJenisWisataActionPerformed
        // TODO add your handling code here:
        FormJenisWisata jenisWisata = new FormJenisWisata();
        jenisWisata.setVisible(true);
    }//GEN-LAST:event_menuJenisWisataActionPerformed

    private void menuPaketTravelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPaketTravelActionPerformed
        // TODO add your handling code here:
        FormPaketTravel paketTravel = new FormPaketTravel();
        paketTravel.setVisible(true);
    }//GEN-LAST:event_menuPaketTravelActionPerformed

    private void menuPenginapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPenginapanActionPerformed
        // TODO add your handling code here:
        FormPenginapan penginapan=new FormPenginapan();
        penginapan.setVisible(true);
    }//GEN-LAST:event_menuPenginapanActionPerformed

    private void menuTransportasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTransportasiActionPerformed
        // TODO add your handling code here:
        FormTransportasi transportasi =new FormTransportasi();
        transportasi.setVisible(true);
    }//GEN-LAST:event_menuTransportasiActionPerformed

    private void menuUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUserActionPerformed
        // TODO add your handling code here:
        FormUser user = new FormUser();
        user.setVisible(true);
    }//GEN-LAST:event_menuUserActionPerformed

    private void menuWisataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuWisataActionPerformed
        // TODO add your handling code here:
        FormWisata wisata = new FormWisata();
        wisata.setVisible(true);
    }//GEN-LAST:event_menuWisataActionPerformed

    private void menuPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPembayaranActionPerformed
        // TODO add your handling code here:
        FormPembayaran pembayaran = new FormPembayaran();
        pembayaran.setVisible(true);
    }//GEN-LAST:event_menuPembayaranActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        menuController.bersih();
        menuController.logout();
        menuController.nonAktif();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void MenuLaporanPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLaporanPembayaranActionPerformed
        // TODO add your handling code here:
        LaporanPembayaran pembayaran = new LaporanPembayaran();
        pembayaran.setVisible(true);
    }//GEN-LAST:event_MenuLaporanPembayaranActionPerformed

    private void menuLaporanPemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLaporanPemesananActionPerformed
        // TODO add your handling code here:
        LaporanPemesananFinal pemesanan = new LaporanPemesananFinal();
        pemesanan.setVisible(true);
    }//GEN-LAST:event_menuLaporanPemesananActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    public JButton getBtnCancel() {
        return btnCancel;
    }

    public void setBtnCancel(JButton btnCancel) {
        this.btnCancel = btnCancel;
    }

    public JButton getBtnLogin() {
        return btnLogin;
    }

    public void setBtnLogin(JButton btnLogin) {
        this.btnLogin = btnLogin;
    }

    public JButton getBtnLogout() {
        return btnLogout;
    }

    public void setBtnLogout(JButton btnLogout) {
        this.btnLogout = btnLogout;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JMenu getjMenu1() {
        return jMenu1;
    }

    public void setjMenu1(JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    

    public JMenu getjMenu3() {
        return jMenu3;
    }

    public void setjMenu3(JMenu jMenu3) {
        this.jMenu3 = jMenu3;
    }

    public JMenu getjMenu4() {
        return jMenu4;
    }

    public void setjMenu4(JMenu jMenu4) {
        this.jMenu4 = jMenu4;
    }

    public JMenu getjMenu5() {
        return jMenu5;
    }

    public void setjMenu5(JMenu jMenu5) {
        this.jMenu5 = jMenu5;
    }

    public JMenu getjMenu6() {
        return jMenu6;
    }

    public void setjMenu6(JMenu jMenu6) {
        this.jMenu6 = jMenu6;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JMenuBar getjMenuBar2() {
        return jMenuBar2;
    }

    public void setjMenuBar2(JMenuBar jMenuBar2) {
        this.jMenuBar2 = jMenuBar2;
    }

    public JMenuItem getjMenuItem1() {
        return jMenuItem1;
    }

    public void setjMenuItem1(JMenuItem jMenuItem1) {
        this.jMenuItem1 = jMenuItem1;
    }

    public JMenuItem getjMenuItem2() {
        return jMenuItem2;
    }

    public void setjMenuItem2(JMenuItem jMenuItem2) {
        this.jMenuItem2 = jMenuItem2;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JMenuItem getMenuGuide() {
        return menuGuide;
    }

    public void setMenuGuide(JMenuItem menuGuide) {
        this.menuGuide = menuGuide;
    }

    public JMenuItem getMenuJenisPenginapan() {
        return menuJenisPenginapan;
    }

    public void setMenuJenisPenginapan(JMenuItem menuJenisPenginapan) {
        this.menuJenisPenginapan = menuJenisPenginapan;
    }

    public JMenuItem getMenuJenisTransportasi() {
        return menuJenisTransportasi;
    }

    public void setMenuJenisTransportasi(JMenuItem menuJenisTransportasi) {
        this.menuJenisTransportasi = menuJenisTransportasi;
    }

    public JMenuItem getMenuJenisWisata() {
        return menuJenisWisata;
    }

    public void setMenuJenisWisata(JMenuItem menuJenisWisata) {
        this.menuJenisWisata = menuJenisWisata;
    }

    public JMenuItem getMenuPaketTravel() {
        return menuPaketTravel;
    }

    public void setMenuPaketTravel(JMenuItem menuPaketTravel) {
        this.menuPaketTravel = menuPaketTravel;
    }

    public JMenuItem getMenuPembayaran() {
        return menuPembayaran;
    }

    public void setMenuPembayaran(JMenuItem menuPembayaran) {
        this.menuPembayaran = menuPembayaran;
    }

    public JMenuItem getMenuPemesanan() {
        return menuPemesanan;
    }

    public void setMenuPemesanan(JMenuItem menuPemesanan) {
        this.menuPemesanan = menuPemesanan;
    }

    public JMenuItem getMenuPenginapan() {
        return menuPenginapan;
    }

    public void setMenuPenginapan(JMenuItem menuPenginapan) {
        this.menuPenginapan = menuPenginapan;
    }

    public JMenuItem getMenuTransportasi() {
        return menuTransportasi;
    }

    public void setMenuTransportasi(JMenuItem menuTransportasi) {
        this.menuTransportasi = menuTransportasi;
    }

    public JMenuItem getMenuUser() {
        return menuUser;
    }

    public void setMenuUser(JMenuItem menuUser) {
        this.menuUser = menuUser;
    }

    public JMenuItem getMenuWisata() {
        return menuWisata;
    }

    public void setMenuWisata(JMenuItem menuWisata) {
        this.menuWisata = menuWisata;
    }

    public JMenuItem getMenuWisatawan() {
        return menuWisatawan;
    }

    public void setMenuWisatawan(JMenuItem menuWisatawan) {
        this.menuWisatawan = menuWisatawan;
    }

    public JTextField getTxtPassword() {
        return txtPassword;
    }


    public JTextField getTxtUsername() {
        return txtUsername;
    }

    public void setTxtUsername(JTextField txtUsername) {
        this.txtUsername = txtUsername;
    }

    public JMenuItem getMenuLaporanPembayaran() {
        return MenuLaporanPembayaran;
    }

    public void setMenuLaporanPembayaran(JMenuItem MenuLaporanPembayaran) {
        this.MenuLaporanPembayaran = MenuLaporanPembayaran;
    }

    public JMenuItem getMenuLaporanPemesanan() {
        return menuLaporanPemesanan;
    }

    public void setMenuLaporanPemesanan(JMenuItem menuLaporanPemesanan) {
        this.menuLaporanPemesanan = menuLaporanPemesanan;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuLaporanPembayaran;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuGuide;
    private javax.swing.JMenuItem menuJenisPenginapan;
    private javax.swing.JMenuItem menuJenisTransportasi;
    private javax.swing.JMenuItem menuJenisWisata;
    private javax.swing.JMenuItem menuLaporanPemesanan;
    private javax.swing.JMenuItem menuPaketTravel;
    private javax.swing.JMenuItem menuPembayaran;
    private javax.swing.JMenuItem menuPemesanan;
    private javax.swing.JMenuItem menuPenginapan;
    private javax.swing.JMenuItem menuTransportasi;
    private javax.swing.JMenuItem menuUser;
    private javax.swing.JMenuItem menuWisata;
    private javax.swing.JMenuItem menuWisatawan;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
