/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.aidil.view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import org.aidil.controller.JenisPenginapanController;

/**
 *
 * @author Aidil
 */
public class FormJenisPenginapan extends javax.swing.JFrame {

    /**
     * Creates new form FormJenisPenginapan
     */
    JenisPenginapanController jenisPenginapanController;
    public FormJenisPenginapan() {
        initComponents();
        jenisPenginapanController = new JenisPenginapanController(this);
        jenisPenginapanController.bersihForm();
        jenisPenginapanController.tampilTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtidjp = new javax.swing.JTextField();
        txtjp = new javax.swing.JTextField();
        btncjp = new javax.swing.JButton();
        btnijp = new javax.swing.JButton();
        btnejp = new javax.swing.JButton();
        btndjp = new javax.swing.JButton();
        btnccjp = new javax.swing.JButton();
        btnexjp = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbjp = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Jenis Penginapan");

        jLabel2.setText("Jenis Penginapan");

        txtidjp.setText("jTextField1");

        txtjp.setText("jTextField2");
        txtjp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjpActionPerformed(evt);
            }
        });

        btncjp.setText("CARI");
        btncjp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncjpActionPerformed(evt);
            }
        });

        btnijp.setText("INSERT");
        btnijp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnijpActionPerformed(evt);
            }
        });

        btnejp.setText("EDIT");
        btnejp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnejpActionPerformed(evt);
            }
        });

        btndjp.setText("DELETE");
        btndjp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndjpActionPerformed(evt);
            }
        });

        btnccjp.setText("CANCEL");
        btnccjp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnccjpActionPerformed(evt);
            }
        });

        btnexjp.setText("EXIT");
        btnexjp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexjpActionPerformed(evt);
            }
        });

        tbjp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID Jenis Penginapan", "Jenis Penginapan"
            }
        ));
        tbjp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbjpMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbjp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnijp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnejp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndjp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnccjp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnexjp)
                        .addGap(0, 87, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(32, 32, 32)
                                .addComponent(txtjp))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtidjp)))
                        .addGap(18, 18, 18)
                        .addComponent(btncjp)
                        .addGap(69, 69, 69))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtidjp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncjp))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtjp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnijp)
                    .addComponent(btnejp)
                    .addComponent(btndjp)
                    .addComponent(btnccjp)
                    .addComponent(btnexjp))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtjpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjpActionPerformed

    private void btncjpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncjpActionPerformed
        // TODO add your handling code here:
        jenisPenginapanController.cariData();
    }//GEN-LAST:event_btncjpActionPerformed

    private void btnijpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnijpActionPerformed
        // TODO add your handling code here:
        jenisPenginapanController.insert();
        jenisPenginapanController.bersihForm();
        jenisPenginapanController.tampilTable();
    }//GEN-LAST:event_btnijpActionPerformed

    private void btnejpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnejpActionPerformed
        // TODO add your handling code here:
        jenisPenginapanController.update();
        jenisPenginapanController.bersihForm();
        jenisPenginapanController.tampilTable();
    }//GEN-LAST:event_btnejpActionPerformed

    private void btndjpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndjpActionPerformed
        // TODO add your handling code here:
        jenisPenginapanController.delete();
        jenisPenginapanController.bersihForm();
        jenisPenginapanController.tampilTable();
    }//GEN-LAST:event_btndjpActionPerformed

    private void btnccjpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnccjpActionPerformed
        // TODO add your handling code here:\
        jenisPenginapanController.bersihForm();
    }//GEN-LAST:event_btnccjpActionPerformed

    private void btnexjpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexjpActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnexjpActionPerformed

    private void tbjpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbjpMouseClicked
        // TODO add your handling code here:
        jenisPenginapanController.pilihTabel();
        
    }//GEN-LAST:event_tbjpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormJenisPenginapan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormJenisPenginapan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormJenisPenginapan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormJenisPenginapan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormJenisPenginapan().setVisible(true);
            }
        });
    }

    public JButton getBtnccjp() {
        return btnccjp;
    }

    public void setBtnccjp(JButton btnccjp) {
        this.btnccjp = btnccjp;
    }

    public JButton getBtncjp() {
        return btncjp;
    }

    public void setBtncjp(JButton btncjp) {
        this.btncjp = btncjp;
    }

    public JButton getBtndjp() {
        return btndjp;
    }

    public void setBtndjp(JButton btndjp) {
        this.btndjp = btndjp;
    }

    public JButton getBtnejp() {
        return btnejp;
    }

    public void setBtnejp(JButton btnejp) {
        this.btnejp = btnejp;
    }

    public JButton getBtnexjp() {
        return btnexjp;
    }

    public void setBtnexjp(JButton btnexjp) {
        this.btnexjp = btnexjp;
    }

    public JButton getBtnijp() {
        return btnijp;
    }

    public void setBtnijp(JButton btnijp) {
        this.btnijp = btnijp;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTable getTbjp() {
        return tbjp;
    }

    public void setTbjp(JTable tbjp) {
        this.tbjp = tbjp;
    }

    public JTextField getTxtidjp() {
        return txtidjp;
    }

    public void setTxtidjp(JTextField txtidjp) {
        this.txtidjp = txtidjp;
    }

    public JTextField getTxtjp() {
        return txtjp;
    }

    public void setTxtjp(JTextField txtjp) {
        this.txtjp = txtjp;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnccjp;
    private javax.swing.JButton btncjp;
    private javax.swing.JButton btndjp;
    private javax.swing.JButton btnejp;
    private javax.swing.JButton btnexjp;
    private javax.swing.JButton btnijp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbjp;
    private javax.swing.JTextField txtidjp;
    private javax.swing.JTextField txtjp;
    // End of variables declaration//GEN-END:variables
}
