/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.aidil.view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import org.aidil.controller.KotaController;

/**
 *
 * @author Aidil
 */
public class FormKota extends javax.swing.JFrame {

    /**
     * Creates new form FormKota
     */
    KotaController kotaController;
    public FormKota() {
        initComponents();
        kotaController = new KotaController(this);
        kotaController.bersihForm();
        kotaController.tampilTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtidkt = new javax.swing.JTextField();
        txtnkt = new javax.swing.JTextField();
        btnckt = new javax.swing.JButton();
        btnikt = new javax.swing.JButton();
        btnukt = new javax.swing.JButton();
        btndkt = new javax.swing.JButton();
        btncckt = new javax.swing.JButton();
        btnexkt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbkt = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Kota");

        jLabel2.setText("Nama Kota");

        txtidkt.setText("jTextField1");

        txtnkt.setText("jTextField2");

        btnckt.setText("CARI");
        btnckt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncktActionPerformed(evt);
            }
        });

        btnikt.setText("INSERT");
        btnikt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btniktActionPerformed(evt);
            }
        });

        btnukt.setText("UPDATE");
        btnukt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuktActionPerformed(evt);
            }
        });

        btndkt.setText("DELETE");
        btndkt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndktActionPerformed(evt);
            }
        });

        btncckt.setText("CANCEL");
        btncckt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnccktActionPerformed(evt);
            }
        });

        btnexkt.setText("EXIT");
        btnexkt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexktActionPerformed(evt);
            }
        });

        tbkt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID Kota", "Nama Kota"
            }
        ));
        tbkt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbktMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbkt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtnkt))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(34, 34, 34)
                                .addComponent(txtidkt)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnckt)
                        .addGap(81, 81, 81))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnikt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnukt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndkt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncckt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnexkt)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtidkt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnckt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnkt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnikt)
                    .addComponent(btnukt)
                    .addComponent(btndkt)
                    .addComponent(btncckt)
                    .addComponent(btnexkt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncktActionPerformed
        // TODO add your handling code here:
        kotaController.cariData();
    }//GEN-LAST:event_btncktActionPerformed

    private void btniktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btniktActionPerformed
        // TODO add your handling code here:
        kotaController.insert();
        kotaController.bersihForm();
        kotaController.tampilTable();
    }//GEN-LAST:event_btniktActionPerformed

    private void btnuktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuktActionPerformed
        // TODO add your handling code here:
        kotaController.update();
        kotaController.bersihForm();
        kotaController.tampilTable();
    }//GEN-LAST:event_btnuktActionPerformed

    private void btndktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndktActionPerformed
        // TODO add your handling code here:
        kotaController.delete();
        kotaController.bersihForm();
        kotaController.tampilTable();
    }//GEN-LAST:event_btndktActionPerformed

    private void btnccktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnccktActionPerformed
        // TODO add your handling code here:
        kotaController.bersihForm();
    }//GEN-LAST:event_btnccktActionPerformed

    private void btnexktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexktActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnexktActionPerformed

    private void tbktMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbktMouseClicked
        // TODO add your handling code here:
        kotaController.pilihTabel();
    }//GEN-LAST:event_tbktMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKota().setVisible(true);
            }
        });
    }

    public JButton getBtncckt() {
        return btncckt;
    }

    public void setBtncckt(JButton btncckt) {
        this.btncckt = btncckt;
    }

    public JButton getBtnckt() {
        return btnckt;
    }

    public void setBtnckt(JButton btnckt) {
        this.btnckt = btnckt;
    }

    public JButton getBtndkt() {
        return btndkt;
    }

    public void setBtndkt(JButton btndkt) {
        this.btndkt = btndkt;
    }

    public JButton getBtnexkt() {
        return btnexkt;
    }

    public void setBtnexkt(JButton btnexkt) {
        this.btnexkt = btnexkt;
    }

    public JButton getBtnikt() {
        return btnikt;
    }

    public void setBtnikt(JButton btnikt) {
        this.btnikt = btnikt;
    }

    public JButton getBtnukt() {
        return btnukt;
    }

    public void setBtnukt(JButton btnukt) {
        this.btnukt = btnukt;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JTextField getTxtidkt() {
        return txtidkt;
    }

    public void setTxtidkt(JTextField txtidkt) {
        this.txtidkt = txtidkt;
    }

    public JTextField getTxtnkt() {
        return txtnkt;
    }

    public void setTxtnkt(JTextField txtnkt) {
        this.txtnkt = txtnkt;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTable getTbkt() {
        return tbkt;
    }

    public void setTbkt(JTable tbkt) {
        this.tbkt = tbkt;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncckt;
    private javax.swing.JButton btnckt;
    private javax.swing.JButton btndkt;
    private javax.swing.JButton btnexkt;
    private javax.swing.JButton btnikt;
    private javax.swing.JButton btnukt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbkt;
    private javax.swing.JTextField txtidkt;
    private javax.swing.JTextField txtnkt;
    // End of variables declaration//GEN-END:variables
}
