/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.aidil.view;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import org.aidil.controller.PenginapanController;

/**
 *
 * @author Aidil
 */
public class FormPenginapan extends javax.swing.JFrame {

    /**
     * Creates new form FormPenginapan
     */
    PenginapanController penginapanController;
    public FormPenginapan() {
        initComponents();
        penginapanController = new PenginapanController(this);
        penginapanController.bersihForm();
        penginapanController.isiPenginapan();
        penginapanController.tampilTable();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtidp = new javax.swing.JTextField();
        txtnp = new javax.swing.JTextField();
        cbidjp = new javax.swing.JComboBox<>();
        btcjp = new javax.swing.JButton();
        btnijp = new javax.swing.JButton();
        btnejp = new javax.swing.JButton();
        btndjp = new javax.swing.JButton();
        btnccjp = new javax.swing.JButton();
        btnexjp = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbjp = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txttp = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Penginapan");

        jLabel2.setText("Nama Penginapan");

        jLabel3.setText("ID Jenis Penginapan");

        txtidp.setText("jTextField1");

        txtnp.setText("jTextField2");

        cbidjp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btcjp.setText("CARI");
        btcjp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcjpActionPerformed(evt);
            }
        });

        btnijp.setText("INSERT");
        btnijp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnijpActionPerformed(evt);
            }
        });

        btnejp.setText("EDIT");
        btnejp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnejpActionPerformed(evt);
            }
        });

        btndjp.setText("DELETE");
        btndjp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndjpActionPerformed(evt);
            }
        });

        btnccjp.setText("CANCEL");
        btnccjp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnccjpActionPerformed(evt);
            }
        });

        btnexjp.setText("EXIT");
        btnexjp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexjpActionPerformed(evt);
            }
        });

        tbjp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Penginapan", "Nama Penginapan", "ID Jenis Penginapan", "Tarif Penginapan"
            }
        ));
        jScrollPane2.setViewportView(tbjp);

        jLabel4.setText("Tarif Penginapan");

        txttp.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnijp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnejp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btndjp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnccjp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnexjp))
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addComponent(txtidp, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txttp)
                                    .addComponent(txtnp, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                    .addComponent(cbidjp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(btcjp)
                        .addGap(75, 75, 75))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtidp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btcjp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtnp, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbidjp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txttp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnijp)
                    .addComponent(btnejp)
                    .addComponent(btndjp)
                    .addComponent(btnccjp)
                    .addComponent(btnexjp))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btcjpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcjpActionPerformed
        // TODO add your handling code here:
        penginapanController.cariData();
    }//GEN-LAST:event_btcjpActionPerformed

    private void btnijpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnijpActionPerformed
        // TODO add your handling code here:
        penginapanController.insert();
        penginapanController.bersihForm();
        penginapanController.tampilTable();
    }//GEN-LAST:event_btnijpActionPerformed

    private void btnejpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnejpActionPerformed
        // TODO add your handling code here:
        penginapanController.update();
        penginapanController.bersihForm();
        penginapanController.tampilTable();
    }//GEN-LAST:event_btnejpActionPerformed

    private void btndjpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndjpActionPerformed
        // TODO add your handling code here:
        penginapanController.delete();
        penginapanController.bersihForm();
        penginapanController.tampilTable();
    }//GEN-LAST:event_btndjpActionPerformed

    private void btnccjpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnccjpActionPerformed
        // TODO add your handling code here:
        penginapanController.bersihForm();
    }//GEN-LAST:event_btnccjpActionPerformed

    private void btnexjpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexjpActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnexjpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPenginapan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPenginapan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPenginapan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPenginapan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPenginapan().setVisible(true);
            }
        });
    }

    public JButton getBtcjp() {
        return btcjp;
    }

    public void setBtcjp(JButton btcjp) {
        this.btcjp = btcjp;
    }

    public JButton getBtnccjp() {
        return btnccjp;
    }

    public void setBtnccjp(JButton btnccjp) {
        this.btnccjp = btnccjp;
    }

    public JButton getBtndjp() {
        return btndjp;
    }

    public void setBtndjp(JButton btndjp) {
        this.btndjp = btndjp;
    }

    public JButton getBtnejp() {
        return btnejp;
    }

    public void setBtnejp(JButton btnejp) {
        this.btnejp = btnejp;
    }

    public JButton getBtnexjp() {
        return btnexjp;
    }

    public void setBtnexjp(JButton btnexjp) {
        this.btnexjp = btnexjp;
    }

    public JButton getBtnijp() {
        return btnijp;
    }

    public void setBtnijp(JButton btnijp) {
        this.btnijp = btnijp;
    }

    public JComboBox<String> getCbidjp() {
        return cbidjp;
    }

    public void setCbidjp(JComboBox<String> cbidjp) {
        this.cbidjp = cbidjp;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public JTable getTbjp() {
        return tbjp;
    }

    public void setTbjp(JTable tbjp) {
        this.tbjp = tbjp;
    }

    public JTextField getTxtidp() {
        return txtidp;
    }

    public void setTxtidp(JTextField txtidp) {
        this.txtidp = txtidp;
    }

    public JTextField getTxtnp() {
        return txtnp;
    }

    public void setTxtnp(JTextField txtnp) {
        this.txtnp = txtnp;
    }

    public PenginapanController getPenginapanController() {
        return penginapanController;
    }

    public void setPenginapanController(PenginapanController penginapanController) {
        this.penginapanController = penginapanController;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JTextField getTxttp() {
        return txttp;
    }

    public void setTxttp(JTextField txttp) {
        this.txttp = txttp;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcjp;
    private javax.swing.JButton btnccjp;
    private javax.swing.JButton btndjp;
    private javax.swing.JButton btnejp;
    private javax.swing.JButton btnexjp;
    private javax.swing.JButton btnijp;
    private javax.swing.JComboBox<String> cbidjp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbjp;
    private javax.swing.JTextField txtidp;
    private javax.swing.JTextField txtnp;
    private javax.swing.JTextField txttp;
    // End of variables declaration//GEN-END:variables
}
