/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.aidil.view;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import org.aidil.controller.TransportasiController;

/**
 *
 * @author Aidil
 */
public class FormTransportasi extends javax.swing.JFrame {

    /**
     * Creates new form FormTransportasi
     */
    TransportasiController transportasiController;
    public FormTransportasi() {
        initComponents();
        transportasiController = new TransportasiController(this);
        transportasiController.bersihForm();
        transportasiController.isiTransportasi();
        transportasiController.tampilTable();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtidt = new javax.swing.JTextField();
        txtnk = new javax.swing.JTextField();
        cbidjt = new javax.swing.JComboBox<>();
        txtst = new javax.swing.JTextField();
        btnct = new javax.swing.JButton();
        btnit = new javax.swing.JButton();
        btnet = new javax.swing.JButton();
        btndt = new javax.swing.JButton();
        btncct = new javax.swing.JButton();
        btnext = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbt = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txttt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Transportasi");

        jLabel2.setText("Nama Kendaraan");

        jLabel3.setText("ID Jenis Transportasi");

        jLabel4.setText("Status");

        txtidt.setText("jTextField1");

        txtnk.setText("jTextField2");

        cbidjt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtst.setText("txts");
        txtst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstActionPerformed(evt);
            }
        });

        btnct.setText("CARI");
        btnct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnctActionPerformed(evt);
            }
        });

        btnit.setText("INSERT");
        btnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnitActionPerformed(evt);
            }
        });

        btnet.setText("EDIT");
        btnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnetActionPerformed(evt);
            }
        });

        btndt.setText("DELETE");
        btndt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndtActionPerformed(evt);
            }
        });

        btncct.setText("CANCEL");
        btncct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncctActionPerformed(evt);
            }
        });

        btnext.setText("EXIT");
        btnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnextActionPerformed(evt);
            }
        });

        tbt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Transportasi", "Nama Kendaraa", "ID Jenis Transportasi", "Status", "Tarif Transportasi"
            }
        ));
        jScrollPane1.setViewportView(tbt);

        jLabel5.setText("Tarif Transportasi");

        txttt.setText("jTextField1");
        txttt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtttActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbidjt, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtnk, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtidt)
                            .addComponent(txtst)
                            .addComponent(txttt))
                        .addGap(18, 18, 18)
                        .addComponent(btnct)
                        .addGap(185, 185, 185))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btndt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btncct)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnext)))
                        .addGap(0, 98, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtidt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnct))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbidjt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txttt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnit)
                    .addComponent(btnet)
                    .addComponent(btndt)
                    .addComponent(btncct)
                    .addComponent(btnext))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(293, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstActionPerformed

    private void btnctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnctActionPerformed
        // TODO add your handling code here:
        transportasiController.cariData();
    }//GEN-LAST:event_btnctActionPerformed

    private void btnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnitActionPerformed
        // TODO add your handling code here:
        transportasiController.insert();
        transportasiController.bersihForm();
        transportasiController.tampilTable();
    }//GEN-LAST:event_btnitActionPerformed

    private void btnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnetActionPerformed
        // TODO add your handling code here:
        transportasiController.update();
        transportasiController.bersihForm();
        transportasiController.tampilTable();
    }//GEN-LAST:event_btnetActionPerformed

    private void btndtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndtActionPerformed
        // TODO add your handling code here:
        transportasiController.delete();
        transportasiController.bersihForm();
        transportasiController.tampilTable();
    }//GEN-LAST:event_btndtActionPerformed

    private void btncctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncctActionPerformed
        // TODO add your handling code here:
        transportasiController.bersihForm();
    }//GEN-LAST:event_btncctActionPerformed

    private void btnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnextActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnextActionPerformed

    private void txtttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtttActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTransportasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTransportasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTransportasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTransportasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTransportasi().setVisible(true);
            }
        });
    }

    public JButton getBtncct() {
        return btncct;
    }

    public void setBtncct(JButton btncct) {
        this.btncct = btncct;
    }

    public JButton getBtnct() {
        return btnct;
    }

    public void setBtnct(JButton btnct) {
        this.btnct = btnct;
    }

    public JButton getBtndt() {
        return btndt;
    }

    public void setBtndt(JButton btndt) {
        this.btndt = btndt;
    }

    public JButton getBtnet() {
        return btnet;
    }

    public void setBtnet(JButton btnet) {
        this.btnet = btnet;
    }

    public JButton getBtnext() {
        return btnext;
    }

    public void setBtnext(JButton btnext) {
        this.btnext = btnext;
    }

    public JButton getBtnit() {
        return btnit;
    }

    public void setBtnit(JButton btnit) {
        this.btnit = btnit;
    }

    public JComboBox<String> getCbidjt() {
        return cbidjt;
    }

    public void setCbidjt(JComboBox<String> cbidjt) {
        this.cbidjt = cbidjt;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JTextField getjTextField3() {
        return txtst;
    }

    public void setjTextField3(JTextField jTextField3) {
        this.txtst = jTextField3;
    }

    public JTextField getTxtidt() {
        return txtidt;
    }

    public void setTxtidt(JTextField txtidt) {
        this.txtidt = txtidt;
    }

    public JTextField getTxtnk() {
        return txtnk;
    }

    public void setTxtnk(JTextField txtnk) {
        this.txtnk = txtnk;
    }

    public JTextField getTxtst() {
        return txtst;
    }

    public void setTxtst(JTextField txtst) {
        this.txtst = txtst;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTable getTbt() {
        return tbt;
    }

    public void setTbt(JTable tbt) {
        this.tbt = tbt;
    }

    public TransportasiController getTransportasiController() {
        return transportasiController;
    }

    public void setTransportasiController(TransportasiController transportasiController) {
        this.transportasiController = transportasiController;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JTextField getTxttt() {
        return txttt;
    }

    public void setTxttt(JTextField txttt) {
        this.txttt = txttt;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncct;
    private javax.swing.JButton btnct;
    private javax.swing.JButton btndt;
    private javax.swing.JButton btnet;
    private javax.swing.JButton btnext;
    private javax.swing.JButton btnit;
    private javax.swing.JComboBox<String> cbidjt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbt;
    private javax.swing.JTextField txtidt;
    private javax.swing.JTextField txtnk;
    private javax.swing.JTextField txtst;
    private javax.swing.JTextField txttt;
    // End of variables declaration//GEN-END:variables
}
