/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.aidil.view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import org.aidil.controller.KulinerController;

/**
 *
 * @author Aidil
 */
public class FormKuliner extends javax.swing.JFrame {

    /**
     * Creates new form FormKuliner
     */
    KulinerController kulinerController;
    public FormKuliner() {
        initComponents();
        kulinerController = new KulinerController(this);
        kulinerController.bersihForm();
        kulinerController.tampilTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtidk = new javax.swing.JTextField();
        txtnk = new javax.swing.JTextField();
        btnck = new javax.swing.JButton();
        btnik = new javax.swing.JButton();
        btnek = new javax.swing.JButton();
        tbndk = new javax.swing.JButton();
        btncck = new javax.swing.JButton();
        btnexk = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbk = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Kuliner");

        jLabel2.setText("Nama");

        txtidk.setText("jTextField1");

        txtnk.setText("jTextField2");

        btnck.setText("CARI");
        btnck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnckActionPerformed(evt);
            }
        });

        btnik.setText("INSERT");
        btnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnikActionPerformed(evt);
            }
        });

        btnek.setText("EDIT");
        btnek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnekActionPerformed(evt);
            }
        });

        tbndk.setText("DELETE");
        tbndk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbndkActionPerformed(evt);
            }
        });

        btncck.setText("CANCEL");
        btncck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncckActionPerformed(evt);
            }
        });

        btnexk.setText("EXIT");
        btnexk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexkActionPerformed(evt);
            }
        });

        tbk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID Kuliner", "Nama"
            }
        ));
        tbk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbkMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbk);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 72, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(28, 28, 28)
                                .addComponent(txtidk))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(47, 47, 47)
                                .addComponent(txtnk)))
                        .addGap(18, 18, 18)
                        .addComponent(btnck)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnek)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbndk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnexk)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtidk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnck))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnik)
                    .addComponent(btnek)
                    .addComponent(tbndk)
                    .addComponent(btncck)
                    .addComponent(btnexk))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnckActionPerformed
        // TODO add your handling code here:
        kulinerController.cariData();
    }//GEN-LAST:event_btnckActionPerformed

    private void btnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnikActionPerformed
        // TODO add your handling code here:
        kulinerController.insert();
        kulinerController.bersihForm();
        kulinerController.tampilTable();
    }//GEN-LAST:event_btnikActionPerformed

    private void btnekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnekActionPerformed
        // TODO add your handling code here:
        kulinerController.update();
        kulinerController.bersihForm();
        kulinerController.tampilTable();
    }//GEN-LAST:event_btnekActionPerformed

    private void tbndkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbndkActionPerformed
        // TODO add your handling code here:
        kulinerController.delete();
        kulinerController.bersihForm();
        kulinerController.tampilTable();
    }//GEN-LAST:event_tbndkActionPerformed

    private void btncckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncckActionPerformed
        // TODO add your handling code here:
        kulinerController.bersihForm();
    }//GEN-LAST:event_btncckActionPerformed

    private void btnexkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexkActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnexkActionPerformed

    private void tbkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbkMouseClicked
        // TODO add your handling code here:
        kulinerController.pilihTabel();
    }//GEN-LAST:event_tbkMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKuliner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKuliner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKuliner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKuliner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKuliner().setVisible(true);
            }
        });
    }

    public JButton getBtncck() {
        return btncck;
    }

    public void setBtncck(JButton btncck) {
        this.btncck = btncck;
    }

    public JButton getBtnck() {
        return btnck;
    }

    public void setBtnck(JButton btnck) {
        this.btnck = btnck;
    }

    public JButton getBtnek() {
        return btnek;
    }

    public void setBtnek(JButton btnek) {
        this.btnek = btnek;
    }

    public JButton getBtnexk() {
        return btnexk;
    }

    public void setBtnexk(JButton btnexk) {
        this.btnexk = btnexk;
    }

    public JButton getBtnik() {
        return btnik;
    }

    public void setBtnik(JButton btnik) {
        this.btnik = btnik;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTable getTbk() {
        return tbk;
    }

    public void setTbk(JTable tbk) {
        this.tbk = tbk;
    }

    public JButton getTbndk() {
        return tbndk;
    }

    public void setTbndk(JButton tbndk) {
        this.tbndk = tbndk;
    }

    public JTextField getTxtidk() {
        return txtidk;
    }

    public void setTxtidk(JTextField txtidk) {
        this.txtidk = txtidk;
    }

    public JTextField getTxtnk() {
        return txtnk;
    }

    public void setTxtnk(JTextField txtnk) {
        this.txtnk = txtnk;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncck;
    private javax.swing.JButton btnck;
    private javax.swing.JButton btnek;
    private javax.swing.JButton btnexk;
    private javax.swing.JButton btnik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbk;
    private javax.swing.JButton tbndk;
    private javax.swing.JTextField txtidk;
    private javax.swing.JTextField txtnk;
    // End of variables declaration//GEN-END:variables
}
