/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.aidil.view;

import datechooser.beans.DateChooserCombo;
import java.awt.Dimension;
import java.text.SimpleDateFormat;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import org.aidil.controller.PemesananController;

/**
 *
 * @author Aidil
 */
public class FormPemesanan extends javax.swing.JFrame {

    /** Creates new form FormPemesanan */
    PemesananController pemesananController;
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    public FormPemesanan() {
        initComponents();
        pemesananController = new PemesananController(this);
        pemesananController.bersihForm();
        pemesananController.tampilTable();
        dctp.setDateFormat(dateFormat);
        cbpkt.removeAllItems();
        cbpkt.addItem("paket");
        cbpkt.addItem("non paket ");
        dctp.setCalendarPreferredSize(new Dimension(350,200));
    }


    public JButton getBtn1() {
        return btnwisata;
    }

    public void setBtn1(JButton btn1) {
        this.btnwisata = btn1;
    }

    public JTextField getTvIdGuide() {
        return tvIdGuide;
    }

    public void setTvIdGuide(JTextField tvIdGuide) {
        this.tvIdGuide = tvIdGuide;
    }

    public JTextField getTvNameGuide() {
        return tvNameGuide;
    }

    public void setTvNameGuide(JTextField tvNameGuide) {
        this.tvNameGuide = tvNameGuide;
    }

    public JTextField getTvIdPaket() {
        return tvIdPaket;
    }

    public void setTvIdPaket(JTextField tvIdPaket) {
        this.tvIdPaket = tvIdPaket;
    }

    public JTextField getTvIdWisata() {
        return tvIdWisata;
    }

    public void setTvIdWisata(JTextField tvIdWisata) {
        this.tvIdWisata = tvIdWisata;
    }
    

    public JTextField getTvIdwisatawan() {
        return tvIdwisatawan;
    }

    public void setTvIdwisatawan(JTextField tvIdwisatawan) {
        this.tvIdwisatawan = tvIdwisatawan;
    }

    public JTextField getTvNamaWisata() {
        return tvNamaWisata;
    }

    public void setTvNamaWisata(JTextField tvNamaWisata) {
        this.tvNamaWisata = tvNamaWisata;
    }

    public JTextField getTvNamaWisatawan() {
        return tvNamaWisatawan;
    }

    public void setTvNamaWisatawan(JTextField tvNamaWisatawan) {
        this.tvNamaWisatawan = tvNamaWisatawan;
    }

    public JTextField getTvnamakendaraan() {
        return tvnamakendaraan;
    }

    public void setTvnamakendaraan(JTextField tvnamakendaraan) {
        this.tvnamakendaraan = tvnamakendaraan;
    }

    public JTextField getTvNamaPenginapan() {
        return tvNamaPenginapan;
    }

    public void setTvNamaPenginapan(JTextField tvNamaPenginapan) {
        this.tvNamaPenginapan = tvNamaPenginapan;
    }
    
    
    
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtidp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tvIdGuide = new javax.swing.JTextField();
        tvIdwisatawan = new javax.swing.JTextField();
        tvIdWisata = new javax.swing.JTextField();
        tvIdTransportasi = new javax.swing.JTextField();
        tvIdPenginapan = new javax.swing.JTextField();
        tvLama = new javax.swing.JTextField();
        tvJumlah = new javax.swing.JTextField();
        dctp = new datechooser.beans.DateChooserCombo();
        btncps = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cbpkt = new javax.swing.JComboBox<>();
        btnwisata = new javax.swing.JButton();
        btnips = new javax.swing.JButton();
        btnups = new javax.swing.JButton();
        btndps = new javax.swing.JButton();
        btnccps = new javax.swing.JButton();
        btnexps = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        tvIdPaket = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbps = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        tvNameGuide = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tvNamaWisatawan = new javax.swing.JTextField();
        btnpaket = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        tvNamaWisata = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tvnamakendaraan = new javax.swing.JTextField();
        btntransportasi = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        tvNamaPenginapan = new javax.swing.JTextField();
        btnpenginapan = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        tvtarifGuide = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tvTarifWisata = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tvTarifTransportasi = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tvTarifPenginapan = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tvTotalBayar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Pemesanan");

        jLabel2.setText("ID Guide");

        jLabel3.setText("ID Wisatawan");

        jLabel4.setText("Pilih Paket");

        txtidp.setText("jTextField1");

        jLabel5.setText("ID Wisata");

        jLabel6.setText("ID Transportasi");

        jLabel7.setText("ID Penginapan");

        jLabel8.setText("Lama Wisata");

        jLabel9.setText("Jumlah Rombongan");

        jLabel10.setText("Tanggal Perjalanan");

        tvIdGuide.setText("jTextField2");

        tvIdwisatawan.setText("jTextField3");

        btncps.setText("CARI");
        btncps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncpsActionPerformed(evt);
            }
        });

        jButton2.setText(".....");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText(".....");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cbpkt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbpkt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbpktItemStateChanged(evt);
            }
        });
        cbpkt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbpktActionPerformed(evt);
            }
        });

        btnwisata.setText(".....");
        btnwisata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnwisataActionPerformed(evt);
            }
        });

        btnips.setText("INSERT");
        btnips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnipsActionPerformed(evt);
            }
        });

        btnups.setText("UPDATE");
        btnups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupsActionPerformed(evt);
            }
        });

        btndps.setText("DELETE");
        btndps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndpsActionPerformed(evt);
            }
        });

        btnccps.setText("CANCEL");
        btnccps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnccpsActionPerformed(evt);
            }
        });

        btnexps.setText("EXIT");
        btnexps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexpsActionPerformed(evt);
            }
        });

        jLabel11.setText("ID Paket");

        tbps.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Pemesanan", "ID Guide", "ID Wisatawan", "Pilih Paket", "ID Paket Travel", "ID Wisata", "ID Transportasi", "ID Penginapan", "Lama Wisata", "Jumlah Rombongan", "Tanggal Perjalanan"
            }
        ));
        jScrollPane1.setViewportView(tbps);

        jLabel12.setText("Nama Guide");

        jLabel13.setText("Nama Wisatawan");

        btnpaket.setText(".....");
        btnpaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpaketActionPerformed(evt);
            }
        });

        jLabel14.setText("Nama Wisata");

        jLabel15.setText("Nama Kendaraan");

        btntransportasi.setText(".....");
        btntransportasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntransportasiActionPerformed(evt);
            }
        });

        jLabel16.setText("Nama Penginapan");

        btnpenginapan.setText(".....");
        btnpenginapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpenginapanActionPerformed(evt);
            }
        });

        jLabel17.setText("Tarif Guide");

        jLabel18.setText("Tarif Wisata");

        jLabel19.setText("Tarif Transportasi");

        jLabel20.setText("Tarif Penginapan");

        jButton1.setText("Hitung");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tvTotalBayar.setText("Total Bayar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tvTarifWisata, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tvtarifGuide, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tvNamaWisata, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tvNamaWisatawan, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tvNameGuide, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tvIdPaket, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtidp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                    .addComponent(tvIdGuide, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tvIdwisatawan, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tvIdWisata, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbpkt, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btncps)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton2)
                                            .addComponent(jButton3)
                                            .addComponent(btnwisata)
                                            .addComponent(btnpaket))
                                        .addGap(133, 133, 133)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel20))
                                        .addGap(48, 48, 48)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dctp, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(tvnamakendaraan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                                    .addComponent(tvTarifPenginapan, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tvNamaPenginapan, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tvJumlah, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tvLama, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tvIdPenginapan, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tvIdTransportasi, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tvTarifTransportasi, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(btnpenginapan)
                                                    .addComponent(btntransportasi)))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(300, 300, 300)
                                .addComponent(btnips)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnups)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btndps)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnccps)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnexps)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(440, 440, 440)
                        .addComponent(tvTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtidp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncps))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tvIdGuide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(tvNameGuide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(tvtarifGuide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tvIdwisatawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(tvNamaWisatawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbpkt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tvIdPaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(btnpaket))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(btnwisata))
                            .addComponent(tvIdWisata, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tvNamaWisata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(tvTarifWisata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tvIdTransportasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(btntransportasi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(tvnamakendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tvTarifTransportasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tvIdPenginapan, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(btnpenginapan))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(tvNamaPenginapan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(tvTarifPenginapan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tvLama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tvJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(dctp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnips)
                    .addComponent(btndps)
                    .addComponent(btnccps)
                    .addComponent(btnexps)
                    .addComponent(btnups))
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tvTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(522, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbpktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbpktActionPerformed
        // TODO add your handling code here:
        if(cbpkt.getSelectedItem()==("paket")){
            btnwisata.setEnabled(false);
            btnpenginapan.setEnabled(false);
            btntransportasi.setEnabled(false);
            
        }else{
            tvIdPaket.setEnabled(false);
            btnpaket.setEnabled(false);
            btnwisata.setEnabled(true);
            btnpenginapan.setEnabled(true);
            btntransportasi.setEnabled(true);
        }
    }//GEN-LAST:event_cbpktActionPerformed

    private void btncpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncpsActionPerformed
        // TODO add your handling code here:
        pemesananController.cariData();
        pemesananController.CariData1();
    }//GEN-LAST:event_btncpsActionPerformed

    private void btnipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnipsActionPerformed
        // TODO add your handling code here:
        pemesananController.insert();
        pemesananController.bersihForm();
        pemesananController.tampilTable();
    }//GEN-LAST:event_btnipsActionPerformed

    private void btnupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupsActionPerformed
        // TODO add your handling code here:
        pemesananController.update();
        pemesananController.bersihForm();
        pemesananController.tampilTable();
    }//GEN-LAST:event_btnupsActionPerformed

    private void btndpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndpsActionPerformed
        // TODO add your handling code here:
        pemesananController.delete();
        pemesananController.bersihForm();
        pemesananController.tampilTable();
    }//GEN-LAST:event_btndpsActionPerformed

    private void btnccpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnccpsActionPerformed
        // TODO add your handling code here:
        pemesananController.bersihForm();
    }//GEN-LAST:event_btnccpsActionPerformed

    private void btnexpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexpsActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnexpsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DialogGuide dialogGuide = new DialogGuide(this, true);
        dialogGuide.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DialogWisatawan dialogWisatawan = new DialogWisatawan(this, true);
        dialogWisatawan.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnpaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpaketActionPerformed
        // TODO add your handling code here:
        DialogPaketTravel dialogPaketTravel = new DialogPaketTravel(this, true);
        dialogPaketTravel.setVisible(true);
    }//GEN-LAST:event_btnpaketActionPerformed

    private void btnwisataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnwisataActionPerformed
        // TODO add your handling code here:
        DialogWisata dialogWisata = new DialogWisata(this, true);
        dialogWisata.setVisible(true);
    }//GEN-LAST:event_btnwisataActionPerformed

    private void btntransportasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntransportasiActionPerformed
        // TODO add your handling code here:
        DialogTransportasi dialogTransportasi = new DialogTransportasi(this, true);
        dialogTransportasi.setVisible(true);
    }//GEN-LAST:event_btntransportasiActionPerformed

    private void btnpenginapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpenginapanActionPerformed
        // TODO add your handling code here:
        DialogPenginapan dialogPenginapan = new DialogPenginapan(this, true);
        dialogPenginapan.setVisible(true);
    }//GEN-LAST:event_btnpenginapanActionPerformed

    private void cbpktItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbpktItemStateChanged
        // TODO add your handling code here:
        if(cbpkt.getSelectedItem()==("paket")){
            tvIdPaket.setEnabled(true);
            btnpaket.setEnabled(true);
            //txtidwpt.setEnabled(false);
            //txtnwpt.setEnabled(false);
            //txtidt.setEnabled(false);
            //txtnkps.setEnabled(false);
            //txtidpp.setEnabled(false);
            //txtnpps.setEnabled(false);
            btnwisata.setEnabled(false);
            btnpenginapan.setEnabled(false);
            btntransportasi.setEnabled(false);
             tvNamaWisata.setText("");
            tvnamakendaraan.setText("");
            tvNamaPenginapan.setText("");
            txtidp.setText("");
            tvIdWisata.setText("");
            tvIdTransportasi.setText("");
            tvIdPenginapan.setText("");
            tvLama.setText("");
            tvIdPaket.setText("");
            tvJumlah.setText("");
            tvTarifWisata.setText("");
            tvTarifTransportasi.setText("");
            tvTarifPenginapan.setText("");
        }else{
            tvIdPaket.setEnabled(false);
            btnpaket.setEnabled(false);
            btnwisata.setEnabled(true);
            btnpenginapan.setEnabled(true);
            btntransportasi.setEnabled(true);
            
            
            tvNamaWisata.setText("");
            tvnamakendaraan.setText("");
            tvNamaPenginapan.setText("");
            txtidp.setText("");
            tvIdWisata.setText("");
            tvIdTransportasi.setText("");
            tvIdPenginapan.setText("");
            tvLama.setText("");
            tvIdPaket.setText("");
            tvJumlah.setText("");
            tvTarifWisata.setText("");
            tvTarifTransportasi.setText("");
            tvTarifPenginapan.setText("");
            
            
        }
        
//        pemesananController.isicombo();
    }//GEN-LAST:event_cbpktItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        pemesananController.Transaksi();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPemesanan().setVisible(true);
            }
        });
    }

    public JButton getBtnpaket() {
        return btnpaket;
    }

    public void setBtnpaket(JButton btnpaket) {
        this.btnpaket = btnpaket;
    }

    public JButton getBtnpenginapan() {
        return btnpenginapan;
    }

    public void setBtnpenginapan(JButton btnpenginapan) {
        this.btnpenginapan = btnpenginapan;
    }

    public JButton getBtntransportasi() {
        return btntransportasi;
    }

    public void setBtntransportasi(JButton btntransportasi) {
        this.btntransportasi = btntransportasi;
    }

    public JButton getBtnwisata() {
        return btnwisata;
    }

    public void setBtnwisata(JButton btnwisata) {
        this.btnwisata = btnwisata;
    }

    public JLabel getjLabel17() {
        return jLabel17;
    }

    public void setjLabel17(JLabel jLabel17) {
        this.jLabel17 = jLabel17;
    }

    public JLabel getjLabel18() {
        return jLabel18;
    }

    public void setjLabel18(JLabel jLabel18) {
        this.jLabel18 = jLabel18;
    }

    public JLabel getjLabel19() {
        return jLabel19;
    }

    public void setjLabel19(JLabel jLabel19) {
        this.jLabel19 = jLabel19;
    }

    public JLabel getjLabel20() {
        return jLabel20;
    }

    public void setjLabel20(JLabel jLabel20) {
        this.jLabel20 = jLabel20;
    }

    public JTextField getTvTotalBayar() {
        return tvTotalBayar;
    }

    public void setTvTotalBayar(JTextField tvTotalBayar) {
        this.tvTotalBayar = tvTotalBayar;
    }
    
    

    public JButton getjButton1() {
        return btnpaket;
    }

    public void setjButton1(JButton jButton1) {
        this.btnpaket = jButton1;
    }

    public JLabel getjLabel13() {
        return jLabel13;
    }

    public void setjLabel13(JLabel jLabel13) {
        this.jLabel13 = jLabel13;
    }

    public JLabel getjLabel14() {
        return jLabel14;
    }

    public void setjLabel14(JLabel jLabel14) {
        this.jLabel14 = jLabel14;
    }

    public JTextField getTxtidwpt() {
        return tvIdWisata;
    }

    public void setTxtidwpt(JTextField txtidwpt) {
        this.tvIdWisata = txtidwpt;
    }

    public JTextField getTxtnwpt() {
        return tvNamaWisata;
    }

    public void setTxtnwpt(JTextField txtnwpt) {
        this.tvNamaWisata = txtnwpt;
    }

    
    public JTextField getTxtnw() {
        return tvNamaWisatawan;
    }

    public void setTxtnw(JTextField txtnw) {
        this.tvNamaWisatawan = txtnw;
    }

    
    public JButton getBtnccps() {
        return btnccps;
    }

    public void setBtnccps(JButton btnccps) {
        this.btnccps = btnccps;
    }

    public JButton getBtncps() {
        return btncps;
    }

    public void setBtncps(JButton btncps) {
        this.btncps = btncps;
    }

    public JButton getBtndps() {
        return btndps;
    }

    public void setBtndps(JButton btndps) {
        this.btndps = btndps;
    }

    public JButton getBtnexps() {
        return btnexps;
    }

    public void setBtnexps(JButton btnexps) {
        this.btnexps = btnexps;
    }

    public JButton getBtnips() {
        return btnips;
    }

    public void setBtnips(JButton btnips) {
        this.btnips = btnips;
    }

    public JButton getBtnups() {
        return btnups;
    }

    public void setBtnups(JButton btnups) {
        this.btnups = btnups;
    }

    public JComboBox<String> getCbpkt() {
        return cbpkt;
    }

    public void setCbpkt(JComboBox<String> cbpkt) {
        this.cbpkt = cbpkt;
    }

    public DateChooserCombo getDctp() {
        return dctp;
    }

    public void setDctp(DateChooserCombo dctp) {
        this.dctp = dctp;
    }

    public JButton getjButton2() {
        return jButton2;
    }

    public void setjButton2(JButton jButton2) {
        this.jButton2 = jButton2;
    }

    public JButton getjButton3() {
        return jButton3;
    }

    public void setjButton3(JButton jButton3) {
        this.jButton3 = jButton3;
    }

    public JButton getjButton4() {
        return btnwisata;
    }

    public void setjButton4(JButton jButton4) {
        this.btnwisata = jButton4;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JTextField getTxtidg() {
        return tvIdGuide;
    }

    public void setTxtidg(JTextField txtidg) {
        this.tvIdGuide = txtidg;
    }

    public JTextField getTxtidp() {
        return txtidp;
    }

    public void setTxtidp(JTextField txtidp) {
        this.txtidp = txtidp;
    }

    public JTextField getTxtidpp() {
        return tvIdPenginapan;
    }

    public void setTxtidpp(JTextField txtidpp) {
        this.tvIdPenginapan = txtidpp;
    }

    public JTextField getTxtidt() {
        return tvIdTransportasi;
    }

    public void setTxtidt(JTextField txtidt) {
        this.tvIdTransportasi = txtidt;
    }

    public JTextField getTxtidw() {
        return tvIdWisata;
    }

    public void setTxtidw(JTextField txtidw) {
        this.tvIdWisata = txtidw;
    }

    public JTextField getTxtidwn() {
        return tvIdwisatawan;
    }

    public void setTxtidwn(JTextField txtidwn) {
        this.tvIdwisatawan = txtidwn;
    }

    public JTextField getTxtjr() {
        return tvJumlah;
    }

    public void setTxtjr(JTextField txtjr) {
        this.tvJumlah = txtjr;
    }

    public JTextField getTxtlw() {
        return tvLama;
    }

    public void setTxtlw(JTextField txtlw) {
        this.tvLama = txtlw;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public void setjLabel11(JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    public JTextField getTxtidpk() {
        return tvIdPaket;
    }

    public void setTxtidpk(JTextField txtidpk) {
        this.tvIdPaket = txtidpk;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTable getTbps() {
        return tbps;
    }

    public void setTbps(JTable tbps) {
        this.tbps = tbps;
    }

    public PemesananController getPemesananController() {
        return pemesananController;
    }

    public void setPemesananController(PemesananController pemesananController) {
        this.pemesananController = pemesananController;
    }

    public SimpleDateFormat getDateFormat() {
        return dateFormat;
    }

    public void setDateFormat(SimpleDateFormat dateFormat) {
        this.dateFormat = dateFormat;
    }

    public JLabel getjLabel12() {
        return jLabel12;
    }

    public void setjLabel12(JLabel jLabel12) {
        this.jLabel12 = jLabel12;
    }

    public JTextField getTxtng() {
        return tvNameGuide;
    }

    public void setTxtng(JTextField txtng) {
        this.tvNameGuide = txtng;
    }

    public JButton getjButton5() {
        return btntransportasi;
    }

    public void setjButton5(JButton jButton5) {
        this.btntransportasi = jButton5;
    }

    public JLabel getjLabel15() {
        return jLabel15;
    }

    public void setjLabel15(JLabel jLabel15) {
        this.jLabel15 = jLabel15;
    }

    public JTextField getTxtnkps() {
        return tvnamakendaraan;
    }

    public void setTxtnkps(JTextField txtnkps) {
        this.tvnamakendaraan = txtnkps;
    }

    public JButton getjButton6() {
        return btnpenginapan;
    }

    public void setjButton6(JButton jButton6) {
        this.btnpenginapan = jButton6;
    }

    public JLabel getjLabel16() {
        return jLabel16;
    }

    public void setjLabel16(JLabel jLabel16) {
        this.jLabel16 = jLabel16;
    }

    public JTextField getTxtnpps() {
        return tvNamaPenginapan;
    }

    public void setTxtnpps(JTextField txtnpps) {
        this.tvNamaPenginapan = txtnpps;
    }

    public JTextField getTxttgps() {
        return tvtarifGuide;
    }

    public void setTxttgps(JTextField txttgps) {
        this.tvtarifGuide = txttgps;
    }

    public JTextField getTxttwps() {
        return tvTarifWisata;
    }

    public void setTxttwps(JTextField txttwps) {
        this.tvTarifWisata = txttwps;
    }

    public JTextField getTxtttps() {
        return tvTarifTransportasi;
    }

    public void setTxtttps(JTextField txtttps) {
        this.tvTarifTransportasi = txtttps;
    }

    public JTextField getTxttpps() {
        return tvTarifPenginapan;
    }

    public void setTxttpps(JTextField txttpps) {
        this.tvTarifPenginapan = txttpps;
    }

    public JTextField getTvHasil() {
        return tvTotalBayar;
    }

    public void setTvHasil(JTextField tvHasil) {
        this.tvTotalBayar = tvHasil;
    }

    public JTextField getTvJumlah() {
        return tvJumlah;
    }

    public void setTvJumlah(JTextField tvJumlah) {
        this.tvJumlah = tvJumlah;
    }

    public JTextField getTvLama() {
        return tvLama;
    }

    public void setTvLama(JTextField tvLama) {
        this.tvLama = tvLama;
    }

    public JTextField getTvTarifPenginapan() {
        return tvTarifPenginapan;
    }

    public void setTvTarifPenginapan(JTextField tvTarifPenginapan) {
        this.tvTarifPenginapan = tvTarifPenginapan;
    }

    public JTextField getTvTarifTransportasi() {
        return tvTarifTransportasi;
    }

    public void setTvTarifTransportasi(JTextField tvTarifTransportasi) {
        this.tvTarifTransportasi = tvTarifTransportasi;
    }

    public JTextField getTvTarifWisata() {
        return tvTarifWisata;
    }

    public void setTvTarifWisata(JTextField tvTarifWisata) {
        this.tvTarifWisata = tvTarifWisata;
    }

    public JTextField getTvtarifGuide() {
        return tvtarifGuide;
    }

    public void setTvtarifGuide(JTextField tvtarifGuide) {
        this.tvtarifGuide = tvtarifGuide;
    }

    public JTextField getTvIdPenginapan() {
        return tvIdPenginapan;
    }

    public void setTvIdPenginapan(JTextField tvIdPenginapan) {
        this.tvIdPenginapan = tvIdPenginapan;
    }

    public JTextField getTvIdTransportasi() {
        return tvIdTransportasi;
    }

    public void setTvIdTransportasi(JTextField tvIdTransportasi) {
        this.tvIdTransportasi = tvIdTransportasi;
    }

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnccps;
    private javax.swing.JButton btncps;
    private javax.swing.JButton btndps;
    private javax.swing.JButton btnexps;
    private javax.swing.JButton btnips;
    private javax.swing.JButton btnpaket;
    private javax.swing.JButton btnpenginapan;
    private javax.swing.JButton btntransportasi;
    private javax.swing.JButton btnups;
    private javax.swing.JButton btnwisata;
    private javax.swing.JComboBox<String> cbpkt;
    private datechooser.beans.DateChooserCombo dctp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbps;
    private javax.swing.JTextField tvIdGuide;
    private javax.swing.JTextField tvIdPaket;
    private javax.swing.JTextField tvIdPenginapan;
    private javax.swing.JTextField tvIdTransportasi;
    private javax.swing.JTextField tvIdWisata;
    private javax.swing.JTextField tvIdwisatawan;
    private javax.swing.JTextField tvJumlah;
    private javax.swing.JTextField tvLama;
    private javax.swing.JTextField tvNamaPenginapan;
    private javax.swing.JTextField tvNamaWisata;
    private javax.swing.JTextField tvNamaWisatawan;
    private javax.swing.JTextField tvNameGuide;
    private javax.swing.JTextField tvTarifPenginapan;
    private javax.swing.JTextField tvTarifTransportasi;
    private javax.swing.JTextField tvTarifWisata;
    private javax.swing.JTextField tvTotalBayar;
    private javax.swing.JTextField tvnamakendaraan;
    private javax.swing.JTextField tvtarifGuide;
    private javax.swing.JTextField txtidp;
    // End of variables declaration//GEN-END:variables

}
