/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.aidil.view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import org.aidil.controller.WisatawanCotroller;

/**
 *
 * @author Aidil
 */
public class FormWisatawan extends javax.swing.JFrame {

    /**
     * Creates new form FormWisatawan
     */
    WisatawanCotroller wisatawanCotroller;
    public FormWisatawan() {
        initComponents();
        wisatawanCotroller = new WisatawanCotroller(this);
        wisatawanCotroller.bersihForm();
        wisatawanCotroller.tampilTable();
    }

    FormWisatawan(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btncw = new javax.swing.JButton();
        txtidw = new javax.swing.JTextField();
        txtnw = new javax.swing.JTextField();
        txtaw = new javax.swing.JTextField();
        txttw = new javax.swing.JTextField();
        btniw = new javax.swing.JButton();
        btnew = new javax.swing.JButton();
        btndw = new javax.swing.JButton();
        btnccw = new javax.swing.JButton();
        btnexw = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbw = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Wisatawan");

        jLabel2.setText("Nama Wisatawan");

        jLabel3.setText("Alamat");

        jLabel4.setText("Telepon");

        btncw.setText("CARI");
        btncw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncwActionPerformed(evt);
            }
        });

        txtidw.setText("jTextField1");

        txtnw.setText("jTextField2");

        txtaw.setText("jTextField3");

        txttw.setText("jTextField4");

        btniw.setText("INSERT");
        btniw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btniwActionPerformed(evt);
            }
        });

        btnew.setText("EDIT");
        btnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnewActionPerformed(evt);
            }
        });

        btndw.setText("DELETE");
        btndw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndwActionPerformed(evt);
            }
        });

        btnccw.setText("CANCEL");
        btnccw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnccwActionPerformed(evt);
            }
        });

        btnexw.setText("EXIT");
        btnexw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexwActionPerformed(evt);
            }
        });

        tbw.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Wisatawan", "Nama Wisatawan", "Alamat", "Telepon"
            }
        ));
        jScrollPane2.setViewportView(tbw);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 26, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btniw)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndw)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnccw)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnexw)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtidw, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(txtnw)
                            .addComponent(txtaw)
                            .addComponent(txttw))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btncw)
                        .addGap(112, 112, 112))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btncw)
                    .addComponent(txtidw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtaw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txttw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btniw)
                    .addComponent(btnew)
                    .addComponent(btndw)
                    .addComponent(btnccw)
                    .addComponent(btnexw))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(307, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnewActionPerformed
        // TODO add your handling code here:
        wisatawanCotroller.update();
        wisatawanCotroller.bersihForm();
        wisatawanCotroller.tampilTable();
    }//GEN-LAST:event_btnewActionPerformed

    private void btncwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncwActionPerformed
        // TODO add your handling code here:
        wisatawanCotroller.cariData();
    }//GEN-LAST:event_btncwActionPerformed

    private void btniwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btniwActionPerformed
        // TODO add your handling code here:
        wisatawanCotroller.insert();
        wisatawanCotroller.bersihForm();
        wisatawanCotroller.tampilTable();
    }//GEN-LAST:event_btniwActionPerformed

    private void btndwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndwActionPerformed
        // TODO add your handling code here:
        wisatawanCotroller.delete();
        wisatawanCotroller.bersihForm();
        wisatawanCotroller.tampilTable();
    }//GEN-LAST:event_btndwActionPerformed

    private void btnccwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnccwActionPerformed
        // TODO add your handling code here:
        wisatawanCotroller.bersihForm();
    }//GEN-LAST:event_btnccwActionPerformed

    private void btnexwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexwActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnexwActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormWisatawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormWisatawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormWisatawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormWisatawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormWisatawan().setVisible(true);
            }
        });
    }

    public JButton getBtnccw() {
        return btnccw;
    }

    public void setBtnccw(JButton btnccw) {
        this.btnccw = btnccw;
    }

    public JButton getBtncw() {
        return btncw;
    }

    public void setBtncw(JButton btncw) {
        this.btncw = btncw;
    }

    public JButton getBtndw() {
        return btndw;
    }

    public void setBtndw(JButton btndw) {
        this.btndw = btndw;
    }

    public JButton getBtnew() {
        return btnew;
    }

    public void setBtnew(JButton btnew) {
        this.btnew = btnew;
    }

    public JButton getBtnexw() {
        return btnexw;
    }

    public void setBtnexw(JButton btnexw) {
        this.btnexw = btnexw;
    }

    public JButton getBtniw() {
        return btniw;
    }

    public void setBtniw(JButton btniw) {
        this.btniw = btniw;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public JTable getTbw() {
        return tbw;
    }

    public void setTbw(JTable tbw) {
        this.tbw = tbw;
    }

    public JTextField getTxtaw() {
        return txtaw;
    }

    public void setTxtaw(JTextField txtaw) {
        this.txtaw = txtaw;
    }

    public JTextField getTxtidw() {
        return txtidw;
    }

    public void setTxtidw(JTextField txtidw) {
        this.txtidw = txtidw;
    }

    public JTextField getTxtnw() {
        return txtnw;
    }

    public void setTxtnw(JTextField txtnw) {
        this.txtnw = txtnw;
    }

    public JTextField getTxttw() {
        return txttw;
    }

    public void setTxttw(JTextField txttw) {
        this.txttw = txttw;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnccw;
    private javax.swing.JButton btncw;
    private javax.swing.JButton btndw;
    private javax.swing.JButton btnew;
    private javax.swing.JButton btnexw;
    private javax.swing.JButton btniw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbw;
    private javax.swing.JTextField txtaw;
    private javax.swing.JTextField txtidw;
    private javax.swing.JTextField txtnw;
    private javax.swing.JTextField txttw;
    // End of variables declaration//GEN-END:variables
}
