/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.aidil.view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import org.aidil.controller.JenisTransportasiController;

/**
 *
 * @author Aidil
 */
public class FormJenisTransportasi extends javax.swing.JFrame {

    /**
     * Creates new form FormJenisTransportasi
     */
    JenisTransportasiController jenisTransportasiController;
    public FormJenisTransportasi() {
        initComponents();
        jenisTransportasiController = new JenisTransportasiController(this);
        jenisTransportasiController.bersihForm();
        jenisTransportasiController.tampilTable();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtidjt = new javax.swing.JTextField();
        txtjt = new javax.swing.JTextField();
        btncjt = new javax.swing.JButton();
        btnijt = new javax.swing.JButton();
        btnejt = new javax.swing.JButton();
        btndjt = new javax.swing.JButton();
        btnccjt = new javax.swing.JButton();
        btnexjt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbjt = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Jenis Transportasi");

        jLabel2.setText("Jenis Transportasi");

        txtidjt.setText("jTextField1");

        txtjt.setText("jTextField2");

        btncjt.setText("CARI");
        btncjt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncjtActionPerformed(evt);
            }
        });

        btnijt.setText("INSERT");
        btnijt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnijtActionPerformed(evt);
            }
        });

        btnejt.setText("EDIT");
        btnejt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnejtActionPerformed(evt);
            }
        });

        btndjt.setText("DELETE");
        btndjt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndjtActionPerformed(evt);
            }
        });

        btnccjt.setText("CANCEL");
        btnccjt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnccjtActionPerformed(evt);
            }
        });

        btnexjt.setText("EXIT");
        btnexjt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexjtActionPerformed(evt);
            }
        });

        tbjt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID Jenis Transportasi", "Jenis Transportasi"
            }
        ));
        tbjt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbjtMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbjt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtjt)
                            .addComponent(txtidjt))
                        .addGap(18, 18, 18)
                        .addComponent(btncjt)
                        .addGap(69, 69, 69))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnijt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnejt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btndjt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnccjt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnexjt)))
                        .addGap(0, 46, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtidjt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncjt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtjt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnijt)
                    .addComponent(btnejt)
                    .addComponent(btndjt)
                    .addComponent(btnccjt)
                    .addComponent(btnexjt))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncjtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncjtActionPerformed
        // TODO add your handling code here:
        jenisTransportasiController.cariData();
    }//GEN-LAST:event_btncjtActionPerformed

    private void btnijtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnijtActionPerformed
        // TODO add your handling code here:
        jenisTransportasiController.insert();
        jenisTransportasiController.bersihForm();
        jenisTransportasiController.tampilTable();
    }//GEN-LAST:event_btnijtActionPerformed

    private void btnejtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnejtActionPerformed
        // TODO add your handling code here:
        jenisTransportasiController.update();
        jenisTransportasiController.bersihForm();
        jenisTransportasiController.tampilTable();
    }//GEN-LAST:event_btnejtActionPerformed

    private void btndjtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndjtActionPerformed
        // TODO add your handling code here:
        jenisTransportasiController.delete();
        jenisTransportasiController.bersihForm();
        jenisTransportasiController.tampilTable();
    }//GEN-LAST:event_btndjtActionPerformed

    private void btnccjtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnccjtActionPerformed
        // TODO add your handling code here:
        jenisTransportasiController.bersihForm();
    }//GEN-LAST:event_btnccjtActionPerformed

    private void btnexjtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexjtActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnexjtActionPerformed

    private void tbjtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbjtMouseClicked
        // TODO add your handling code here:\
        jenisTransportasiController.pilihTabel();
    }//GEN-LAST:event_tbjtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormJenisTransportasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormJenisTransportasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormJenisTransportasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormJenisTransportasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormJenisTransportasi().setVisible(true);
            }
        });
    }

    public JButton getBtnccjt() {
        return btnccjt;
    }

    public void setBtnccjt(JButton btnccjt) {
        this.btnccjt = btnccjt;
    }

    public JButton getBtncjt() {
        return btncjt;
    }

    public void setBtncjt(JButton btncjt) {
        this.btncjt = btncjt;
    }

    public JButton getBtndjt() {
        return btndjt;
    }

    public void setBtndjt(JButton btndjt) {
        this.btndjt = btndjt;
    }

    public JButton getBtnejt() {
        return btnejt;
    }

    public void setBtnejt(JButton btnejt) {
        this.btnejt = btnejt;
    }

    public JButton getBtnexjt() {
        return btnexjt;
    }

    public void setBtnexjt(JButton btnexjt) {
        this.btnexjt = btnexjt;
    }

    public JButton getBtnijt() {
        return btnijt;
    }

    public void setBtnijt(JButton btnijt) {
        this.btnijt = btnijt;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JTextField getTxtidjt() {
        return txtidjt;
    }

    public void setTxtidjt(JTextField txtidjt) {
        this.txtidjt = txtidjt;
    }

    public JTextField getTxtjt() {
        return txtjt;
    }

    public void setTxtjt(JTextField txtjt) {
        this.txtjt = txtjt;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTable getTbjt() {
        return tbjt;
    }

    public void setTbjt(JTable tbjt) {
        this.tbjt = tbjt;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnccjt;
    private javax.swing.JButton btncjt;
    private javax.swing.JButton btndjt;
    private javax.swing.JButton btnejt;
    private javax.swing.JButton btnexjt;
    private javax.swing.JButton btnijt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbjt;
    private javax.swing.JTextField txtidjt;
    private javax.swing.JTextField txtjt;
    // End of variables declaration//GEN-END:variables
}
