/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.aidil.view;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import org.aidil.controller.WisataController;

/**
 *
 * @author Aidil
 */
public class FormWisata extends javax.swing.JFrame {

    /**
     * Creates new form FormWisata
     */
    WisataController wisataController;
    public FormWisata() {
        initComponents();
        wisataController = new WisataController(this);
        wisataController.bersihForm();
        wisataController.isiWisata();
        wisataController.tampilTable();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtidwa = new javax.swing.JTextField();
        txtntwa = new javax.swing.JTextField();
        cbidjw = new javax.swing.JComboBox<>();
        btncwa = new javax.swing.JButton();
        btniwa = new javax.swing.JButton();
        btnewa = new javax.swing.JButton();
        btndwa = new javax.swing.JButton();
        btnccwa = new javax.swing.JButton();
        btnexwa = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbw = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txttw = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Wisata");

        jLabel2.setText("Nama Tempat Wisata");

        jLabel3.setText("ID Jenis Wisata");

        txtidwa.setText("jTextField1");
        txtidwa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidwaActionPerformed(evt);
            }
        });

        txtntwa.setText("jTextField2");

        cbidjw.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btncwa.setText("CARI");
        btncwa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncwaActionPerformed(evt);
            }
        });

        btniwa.setText("INSERT");
        btniwa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btniwaActionPerformed(evt);
            }
        });

        btnewa.setText("EDIT");
        btnewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnewaActionPerformed(evt);
            }
        });

        btndwa.setText("DELETE");
        btndwa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndwaActionPerformed(evt);
            }
        });

        btnccwa.setText("CANCEL");
        btnccwa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnccwaActionPerformed(evt);
            }
        });

        btnexwa.setText("EXIT");
        btnexwa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexwaActionPerformed(evt);
            }
        });

        tbw.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Wisata", "Nama Tempat Wisata", "ID Jenis Wisata", "Tarif Wisata"
            }
        ));
        jScrollPane2.setViewportView(tbw);

        jLabel4.setText("Tarif Wisata");

        txttw.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtntwa)
                            .addComponent(txtidwa)
                            .addComponent(cbidjw, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncwa)
                        .addGap(96, 96, 96))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btniwa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnewa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btndwa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnccwa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnexwa))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(78, 78, 78)
                                .addComponent(txttw))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtidwa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncwa))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtntwa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbidjw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txttw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btniwa)
                    .addComponent(btnewa)
                    .addComponent(btndwa)
                    .addComponent(btnccwa)
                    .addComponent(btnexwa))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncwaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncwaActionPerformed
        // TODO add your handling code here:
        wisataController.cariData();
    }//GEN-LAST:event_btncwaActionPerformed

    private void txtidwaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidwaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidwaActionPerformed

    private void btniwaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btniwaActionPerformed
        // TODO add your handling code here:
        wisataController.tampilTable();
        wisataController.insert();
        wisataController.bersihForm();
        wisataController.tampilTable();
    }//GEN-LAST:event_btniwaActionPerformed

    private void btnewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnewaActionPerformed
        // TODO add your handling code here:
        wisataController.tampilTable();
        wisataController.update();
        wisataController.bersihForm();
    }//GEN-LAST:event_btnewaActionPerformed

    private void btndwaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndwaActionPerformed
        // TODO add your handling code here:
        wisataController.delete();
        wisataController.bersihForm();
        wisataController.tampilTable();
    }//GEN-LAST:event_btndwaActionPerformed

    private void btnccwaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnccwaActionPerformed
        // TODO add your handling code here:
        wisataController.bersihForm();
    }//GEN-LAST:event_btnccwaActionPerformed

    private void btnexwaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexwaActionPerformed
        // TODO add your handling code here: 
        dispose();
    }//GEN-LAST:event_btnexwaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormWisata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormWisata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormWisata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormWisata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormWisata().setVisible(true);
            }
        });
    }

    public JButton getBtnccwa() {
        return btnccwa;
    }

    public void setBtnccwa(JButton btnccwa) {
        this.btnccwa = btnccwa;
    }

    public JButton getBtncwa() {
        return btncwa;
    }

    public void setBtncwa(JButton btncwa) {
        this.btncwa = btncwa;
    }

    public JButton getBtndwa() {
        return btndwa;
    }

    public void setBtndwa(JButton btndwa) {
        this.btndwa = btndwa;
    }

    public JButton getBtnewa() {
        return btnewa;
    }

    public void setBtnewa(JButton btnewa) {
        this.btnewa = btnewa;
    }

    public JButton getBtnexwa() {
        return btnexwa;
    }

    public void setBtnexwa(JButton btnexwa) {
        this.btnexwa = btnexwa;
    }

    public JButton getBtniwa() {
        return btniwa;
    }

    public void setBtniwa(JButton btniwa) {
        this.btniwa = btniwa;
    }

    public JComboBox<String> getCbidjw() {
        return cbidjw;
    }

    public void setCbidjw(JComboBox<String> cbidjw) {
        this.cbidjw = cbidjw;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JTextField getTxtidwa() {
        return txtidwa;
    }

    public void setTxtidwa(JTextField txtidwa) {
        this.txtidwa = txtidwa;
    }

    public JTextField getTxtntwa() {
        return txtntwa;
    }

    public void setTxtntwa(JTextField txtntwa) {
        this.txtntwa = txtntwa;
    }

    public WisataController getWisataController() {
        return wisataController;
    }

    public void setWisataController(WisataController wisataController) {
        this.wisataController = wisataController;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public JTable getTbw() {
        return tbw;
    }

    public void setTbw(JTable tbw) {
        this.tbw = tbw;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JTextField getTxttw() {
        return txttw;
    }

    public void setTxttw(JTextField txttw) {
        this.txttw = txttw;
    }

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnccwa;
    private javax.swing.JButton btncwa;
    private javax.swing.JButton btndwa;
    private javax.swing.JButton btnewa;
    private javax.swing.JButton btnexwa;
    private javax.swing.JButton btniwa;
    private javax.swing.JComboBox<String> cbidjw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbw;
    private javax.swing.JTextField txtidwa;
    private javax.swing.JTextField txtntwa;
    private javax.swing.JTextField txttw;
    // End of variables declaration//GEN-END:variables
}
